export interface PageMetaItem {
  titleFa: string;
  titleEn: string;
  parentPath: string | null;
  parentTitleFa?: string;
  parentTitleEn?: string;
}

export const PAGE_META: Record<string, PageMetaItem> = {
  // PARENT HUBS
  'needs': {
    titleFa: 'نیازمندی‌ها و استقرار',
    titleEn: 'Essentials & Settlement',
    parentPath: null,
  },
  'immigration': {
    titleFa: 'مهاجرت و اقامت',
    titleEn: 'Immigration & Residence',
    parentPath: null,
  },
  'work': {
    titleFa: 'کار و اشتغال',
    titleEn: 'Work & Employment',
    parentPath: null,
  },
  'company': {
    titleFa: 'ثبت شرکت و سرمایه‌گذاری',
    titleEn: 'Business & Investment',
    parentPath: null,
  },
  'study': {
    titleFa: 'تحصیل در رومانی',
    titleEn: 'Study in Romania',
    parentPath: null,
  },
  'romania': {
    titleFa: 'درباره رومانی',
    titleEn: 'About Romania',
    parentPath: null,
  },
  'start-here': {
    titleFa: 'از کجا شروع کنم',
    titleEn: 'Start Here',
    parentPath: null,
  },
  'legal': {
    titleFa: 'حقوقی و شرایط',
    titleEn: 'Legal & Terms',
    parentPath: null,
  },

  // Subpages - NEEDS
  'needs/driving-license': {
    titleFa: 'گواهینامه رانندگی',
    titleEn: 'Driving License',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/first-days-checklist': {
    titleFa: 'چک‌لیست روزهای نخست ورود',
    titleEn: 'First-Days Arrival Checklist',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/housing': {
    titleFa: 'اجاره و خرید مسکن',
    titleEn: 'Renting & Buying Property',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/banking': {
    titleFa: 'افتتاح حساب بانکی',
    titleEn: 'Bank Account Opening',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/certified-translation': {
    titleFa: 'دارالترجمه رسمی',
    titleEn: 'Certified Translation',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/notary-public': {
    titleFa: 'دفتر اسناد رسمی (Notary)',
    titleEn: 'Notary Public',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/iranian-embassy-and-mikhak': {
    titleFa: 'سفارت ایران و سامانه میخک',
    titleEn: 'Iranian Embassy & Mikhak',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/health': {
    titleFa: 'خدمات درمانی و بیمه سلامت',
    titleEn: 'Healthcare & Insurance',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/healthcare': {
    titleFa: 'خدمات درمانی و سلامت',
    titleEn: 'Healthcare & Insurance',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/school': {
    titleFa: 'ثبت‌نام مدارس و معادلسازی مدارک',
    titleEn: 'Schools & Education',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/telecom': {
    titleFa: 'تلفن همراه، اینترنت و تلویزیون',
    titleEn: 'Telecom, Internet & TV',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/sim-internet': {
    titleFa: 'سیم‌کارت و اینترنت',
    titleEn: 'SIM & Internet',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/currency-exchange': {
    titleFa: 'صرافی و پرداخت‌های ارزی',
    titleEn: 'Currency Exchange',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },
  'needs/transportation': {
    titleFa: 'حمل‌ونقل عمومی و بین‌شهری',
    titleEn: 'Public Transportation',
    parentPath: '/needs',
    parentTitleFa: 'نیازمندی‌ها و استقرار',
    parentTitleEn: 'Essentials & Settlement',
  },

  // Subpages - IMMIGRATION
  'immigration/igi-process': {
    titleFa: 'مراحل و نوبت‌دهی IGI',
    titleEn: 'IGI Residency Process',
    parentPath: '/immigration',
    parentTitleFa: 'مهاجرت و اقامت',
    parentTitleEn: 'Immigration & Residence',
  },
  'immigration/residence-renewal': {
    titleFa: 'تمدید کارت اقامت',
    titleEn: 'Residence Renewal',
    parentPath: '/immigration',
    parentTitleFa: 'مهاجرت و اقامت',
    parentTitleEn: 'Immigration & Residence',
  },
  'immigration/family-reunification': {
    titleFa: 'پیوست خانواده',
    titleEn: 'Family Reunification',
    parentPath: '/immigration',
    parentTitleFa: 'مهاجرت و اقامت',
    parentTitleEn: 'Immigration & Residence',
  },
  'immigration/long-term-residence': {
    titleFa: 'اقامت بلندمدت و دائم',
    titleEn: 'Long-Term Residence',
    parentPath: '/immigration',
    parentTitleFa: 'مهاجرت و اقامت',
    parentTitleEn: 'Immigration & Residence',
  },
  'immigration/citizenship': {
    titleFa: 'تابعیت و پاسپورت رومانی',
    titleEn: 'Romanian Citizenship',
    parentPath: '/immigration',
    parentTitleFa: 'مهاجرت و اقامت',
    parentTitleEn: 'Immigration & Residence',
  },

  // Subpages - WORK
  'work/finding-job': {
    titleFa: 'پیدا کردن کار و رزومه‌نویسی',
    titleEn: 'Finding a Job',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },
  'work/find-job': {
    titleFa: 'پیدا کردن کار',
    titleEn: 'Finding a Job',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },
  'work/work-permit': {
    titleFa: 'مجوز کار (Aviz de Muncă)',
    titleEn: 'Work Permit (Aviz de Muncă)',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },
  'work/permit': {
    titleFa: 'مجوز کار',
    titleEn: 'Work Permit',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },
  'work/work-visa': {
    titleFa: 'ویزای کاری (نوع D/AM)',
    titleEn: 'Work Visa (Type D/AM)',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },
  'work/employment-contract': {
    titleFa: 'قرارداد استخدام و حقوق کارمند',
    titleEn: 'Employment Contract',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },
  'work/taxes-salaries': {
    titleFa: 'حقوق و مالیات کارمندی',
    titleEn: 'Salary & Taxes',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },
  'work/tax': {
    titleFa: 'مالیات کار',
    titleEn: 'Work Tax',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },
  'work/insurance': {
    titleFa: 'بیمه اجتماعی و درمانی',
    titleEn: 'Social & Health Insurance',
    parentPath: '/work',
    parentTitleFa: 'کار و اشتغال',
    parentTitleEn: 'Work & Employment',
  },

  // Subpages - COMPANY
  'company/registration': {
    titleFa: 'ثبت شرکت (SRL)',
    titleEn: 'Company Registration (SRL)',
    parentPath: '/company',
    parentTitleFa: 'ثبت شرکت و سرمایه‌گذاری',
    parentTitleEn: 'Business & Investment',
  },
  'company/tax-types': {
    titleFa: 'انواع مالیات شرکتی',
    titleEn: 'Corporate Tax Types',
    parentPath: '/company',
    parentTitleFa: 'ثبت شرکت و سرمایه‌گذاری',
    parentTitleEn: 'Business & Investment',
  },
  'company/bank-account': {
    titleFa: 'حساب بانکی تجاری',
    titleEn: 'Corporate Bank Account',
    parentPath: '/company',
    parentTitleFa: 'ثبت شرکت و سرمایه‌گذاری',
    parentTitleEn: 'Business & Investment',
  },
  'company/residency': {
    titleFa: 'اقامت از طریق ثبت شرکت',
    titleEn: 'Residency via Business',
    parentPath: '/company',
    parentTitleFa: 'ثبت شرکت و سرمایه‌گذاری',
    parentTitleEn: 'Business & Investment',
  },
  'company/real-estate-investment': {
    titleFa: 'سرمایه‌گذاری در املاک',
    titleEn: 'Real Estate Investment',
    parentPath: '/company',
    parentTitleFa: 'ثبت شرکت و سرمایه‌گذاری',
    parentTitleEn: 'Business & Investment',
  },
  'company/startup-tech-investment': {
    titleFa: 'سرمایه‌گذاری استارتاپ و تکنولوژی',
    titleEn: 'Startup & Tech Investment',
    parentPath: '/company',
    parentTitleFa: 'ثبت شرکت و سرمایه‌گذاری',
    parentTitleEn: 'Business & Investment',
  },
  'company/annual-tax-reporting': {
    titleFa: 'گزارش مالیاتی سالانه',
    titleEn: 'Annual Tax Reporting',
    parentPath: '/company',
    parentTitleFa: 'ثبت شرکت و سرمایه‌گذاری',
    parentTitleEn: 'Business & Investment',
  },
  'company/investment': {
    titleFa: 'فرصت‌های سرمایه‌گذاری',
    titleEn: 'Investment Opportunities',
    parentPath: '/company',
    parentTitleFa: 'ثبت شرکت و سرمایه‌گذاری',
    parentTitleEn: 'Business & Investment',
  },

  // Subpages - STUDY
  'study/requirements': {
    titleFa: 'مدارک و الزامات پذیرش',
    titleEn: 'Admission Requirements',
    parentPath: '/study',
    parentTitleFa: 'تحصیل در رومانی',
    parentTitleEn: 'Study in Romania',
  },
  'study/visa-type-d': {
    titleFa: 'ویزای تحصیلی نوع D/SD',
    titleEn: 'Type D/SD Student Visa',
    parentPath: '/study',
    parentTitleFa: 'تحصیل در رومانی',
    parentTitleEn: 'Study in Romania',
  },
  'study/tuition-overview': {
    titleFa: 'شهریه‌های تحصیلی',
    titleEn: 'Tuition Rates',
    parentPath: '/study',
    parentTitleFa: 'تحصیل در رومانی',
    parentTitleEn: 'Study in Romania',
  },
  'study/preparatory-year': {
    titleFa: 'سال زبان (Anul Pregătitor)',
    titleEn: 'Language Preparatory Year',
    parentPath: '/study',
    parentTitleFa: 'تحصیل در رومانی',
    parentTitleEn: 'Study in Romania',
  },
  'study/scholarships': {
    titleFa: 'بورسیه‌های تحصیلی دولتی',
    titleEn: 'Government Scholarships',
    parentPath: '/study',
    parentTitleFa: 'تحصیل در رومانی',
    parentTitleEn: 'Study in Romania',
  },
  'study/part-time-work': {
    titleFa: 'مجوز کار دانشجویی',
    titleEn: 'Student Work Permits',
    parentPath: '/study',
    parentTitleFa: 'تحصیل در رومانی',
    parentTitleEn: 'Study in Romania',
  },

  // Subpages - START HERE
  'start-here/planning-to-come': {
    titleFa: 'برنامه‌ریزی برای ورود',
    titleEn: 'Planning Your Move',
    parentPath: '/start-here',
    parentTitleFa: 'از کجا شروع کنم',
    parentTitleEn: 'Start Here',
  },
  'start-here/arriving-soon': {
    titleFa: 'روزهای پیش از ورود',
    titleEn: 'Arriving Soon',
    parentPath: '/start-here',
    parentTitleFa: 'از کجا شروع کنم',
    parentTitleEn: 'Start Here',
  },
  'start-here/newly-arrived': {
    titleFa: 'تازه‌واردین (۷۲ ساعت اول)',
    titleEn: 'Newly Arrived',
    parentPath: '/start-here',
    parentTitleFa: 'از کجا شروع کنم',
    parentTitleEn: 'Start Here',
  },
  'start-here/settling-in': {
    titleFa: 'استقرار و ماه اول',
    titleEn: 'Settling In',
    parentPath: '/start-here',
    parentTitleFa: 'از کجا شروع کنم',
    parentTitleEn: 'Start Here',
  },
  'start-here/long-term-stay': {
    titleFa: 'اقامت و زندگی بلندمدت',
    titleEn: 'Long-Term Life',
    parentPath: '/start-here',
    parentTitleFa: 'از کجا شروع کنم',
    parentTitleEn: 'Start Here',
  },
  'start-here/citizenship-goal': {
    titleFa: 'هدف‌گذاری تابعیت رومانی',
    titleEn: 'Citizenship Path',
    parentPath: '/start-here',
    parentTitleFa: 'از کجا شروع کنم',
    parentTitleEn: 'Start Here',
  },

  // Subpages - ROMANIA
  'romania/economy': {
    titleFa: 'اقتصاد و بازار مالی',
    titleEn: 'Economy & Markets',
    parentPath: '/romania',
    parentTitleFa: 'درباره رومانی',
    parentTitleEn: 'About Romania',
  },
  'romania/society': {
    titleFa: 'جامعه و زندگی اجتماعی',
    titleEn: 'Society & Social Life',
    parentPath: '/romania',
    parentTitleFa: 'درباره رومانی',
    parentTitleEn: 'About Romania',
  },
  'romania/culture-and-arts': {
    titleFa: 'فرهنگ و هنر',
    titleEn: 'Culture & Arts',
    parentPath: '/romania',
    parentTitleFa: 'درباره رومانی',
    parentTitleEn: 'About Romania',
  },
  'romania/laws-and-regulations': {
    titleFa: 'قوانین و مقررات',
    titleEn: 'Laws & Regulations',
    parentPath: '/romania',
    parentTitleFa: 'درباره رومانی',
    parentTitleEn: 'About Romania',
  },
  'romania/tourism': {
    titleFa: 'گردشگری و جاذبه‌ها',
    titleEn: 'Tourism & Travel',
    parentPath: '/romania',
    parentTitleFa: 'درباره رومانی',
    parentTitleEn: 'About Romania',
  },
  'romania/geography': {
    titleFa: 'جغرافیا و شهرهای اصلی',
    titleEn: 'Geography & Cities',
    parentPath: '/romania',
    parentTitleFa: 'درباره رومانی',
    parentTitleEn: 'About Romania',
  },
  'romania/culture': {
    titleFa: 'فرهنگ و سبک زندگی',
    titleEn: 'Culture & Lifestyle',
    parentPath: '/romania',
    parentTitleFa: 'درباره رومانی',
    parentTitleEn: 'About Romania',
  },
  'romania/history': {
    titleFa: 'تاریخ رومانی',
    titleEn: 'History of Romania',
    parentPath: '/romania',
    parentTitleFa: 'درباره رومانی',
    parentTitleEn: 'About Romania',
  },

  // Subpages - LEGAL
  'legal/privacy': {
    titleFa: 'حریم خصوصی',
    titleEn: 'Privacy Policy',
    parentPath: '/legal',
    parentTitleFa: 'حقوقی و شرایط',
    parentTitleEn: 'Legal & Terms',
  },
  'legal/terms': {
    titleFa: 'شرایط استفاده',
    titleEn: 'Terms of Use',
    parentPath: '/legal',
    parentTitleFa: 'حقوقی و شرایط',
    parentTitleEn: 'Legal & Terms',
  },
  'legal/disclaimer': {
    titleFa: 'سلب مسئولیت',
    titleEn: 'Legal Disclaimer',
    parentPath: '/legal',
    parentTitleFa: 'حقوقی و شرایط',
    parentTitleEn: 'Legal & Terms',
  },
};
