import { RomanianWord, RomanianPhrase } from '@/lib/romanian/types';

/**
 * ماژول احوال‌پرسی و ادب هسته‌ی رومانیایی (dre-p166)
 * ایستگاه ۵ از حوزه‌ی core
 *
 * شامل:
 * - ۱۲ واژه (bon/bună, bine, rău, mai [adv], salut [noun], pa [interj], da, nu, plăcere, revedere, scuză)
 * - ۲۰ عبارت کاربردی با منبع‌دهی دقیق
 * - ثبت سیاست رجیستر روی چهار جفت تعاملی (dumneavoastră فعل جمع voi می‌گیرد)
 * - قاعده وارونگی در noapte bună
 *
 * تمامی اقلام با status: 'draft' و stationId: 'core-greetings' ثبت شده‌اند.
 */

export const CORE_GREETING_WORDS: RomanianWord[] = [
  {
    id: 'w-core-bun',
    lemma: 'bun',
    pos: 'adj',
    translations: {
      en: 'good',
      fa: 'خوب',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/bun',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'صفت پایه با معنای «خوب». صورت مؤنث مفرد آن «bună» در بیشتر احوال‌پرسی‌های روزانه به کار می‌رود.',
      en: 'Base adjective meaning "good". Its feminine singular form "bună" is used in most everyday greetings.',
    },
  },
  {
    id: 'w-core-buna',
    lemma: 'bună',
    pos: 'adj',
    formOf: 'w-core-bun',
    translations: {
      en: 'good (feminine)',
      fa: 'خوب (مؤنث)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/bun',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'صورت مؤنث مفرد صفت bun. در احوال‌پرسی‌ها پیش یا پس از اسم مؤنث می‌آید: bună dimineața، bună ziua، bună seara، noapte bună.',
      en: 'Feminine singular of bun. Used in greetings before or after feminine nouns.',
    },
  },
  {
    id: 'w-core-bine',
    lemma: 'bine',
    pos: 'adv',
    translations: {
      en: 'well / fine',
      fa: 'خوب / به خوبی',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/bine',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید حالت با کاربرد فراوان در پاسخ‌های احوال‌پرسی («Bine, mulțumesc») و تعارفات («Îmi pare bine»).',
      en: 'Adverb widely used in greeting responses ("Bine, mulțumesc") and politeness formulas ("Îmi pare bine").',
    },
  },
  {
    id: 'w-core-rau',
    lemma: 'rău',
    pos: 'adv',
    translations: {
      en: 'bad / badly / sorry',
      fa: 'بد / ناراحت',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/r%C4%83u',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید منفی که در ترکیب با فعل părea عبارت عذرخواهی و تأسف «Îmi pare rău» (متأسفم) را می‌سازد.',
      en: 'Adverb used with verb părea in the expression of apology and sympathy "Îmi pare rău" (I am sorry).',
    },
  },
  {
    id: 'w-core-mai-adv',
    lemma: 'mai',
    pos: 'adv',
    translations: {
      en: 'more / else (in greetings: Ce mai faci?)',
      fa: 'دیگر / بیشتر (در احوال‌پرسی: چه خبر)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/mai',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید احوال‌پرسی و تفضیلی در عبارت‌هایی چون Ce mai faci?. همنگاشت با نام ماه مه، ولی واژه‌ی مستقلی است و رابطه‌ی صرفی با آن ندارد.',
      en: 'Greeting and comparative adverb used in phrases like Ce mai faci?. Homograph of the month May, but an independent word with no inflectional relation.',
    },
  },
  {
    id: 'w-core-salut',
    lemma: 'salut',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'salutul',
    plural: 'saluturi',
    translations: {
      en: 'greeting / hello',
      fa: 'درود / سلام (غیررسمی)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/salut',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'اسم خنثی (salutul / saluturi) که طبق تعریف فرهنگ لغت به صورت ندایی به عنوان سلام و درود غیررسمی (Salut!) نیز به کار می‌رود.',
      en: 'Neuter noun (salutul / saluturi) used as an informal greeting (Salut!) per dictionary definition.',
    },
  },
  {
    id: 'w-core-pa',
    lemma: 'pa',
    pos: 'interj',
    translations: {
      en: 'bye',
      fa: 'خداحافظ (خودمانی)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09 / DOOM 3)',
      url: 'https://dexonline.ro/definitie/pa',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'صوت خداحافظی غیررسمی و صمیمانه میان دوستان و آشنایان نزدیک.',
      en: 'Informal farewell greeting among friends and close acquaintances.',
    },
  },
  {
    id: 'w-core-da',
    lemma: 'da',
    pos: 'adv',
    translations: {
      en: 'yes',
      fa: 'بله / آره',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/da',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-core-nu',
    lemma: 'nu',
    pos: 'adv',
    translations: {
      en: 'no / not',
      fa: 'نه / خیر',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/nu',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-core-placere',
    lemma: 'plăcere',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'plăcerea',
    plural: 'plăceri',
    translations: {
      en: 'pleasure',
      fa: 'لذت / خوشوقتی',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/pl%C4%83cere',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'اسم مؤنث که در لوکوسیون «cu plăcere» (خواهش می‌کنم / با کمال میل) به کار می‌رود.',
      en: 'Feminine noun used in the locution "cu plăcere" (you are welcome / with pleasure).',
    },
  },
  {
    id: 'w-core-revedere',
    lemma: 'revedere',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'revederea',
    plural: 'revederi',
    translations: {
      en: 'seeing again / meeting again',
      fa: 'دیدار دوباره',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/revedere',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'اسم مؤنث با ریشه‌ی فعلی که در لوکوسیون خداحافظی رسمی «la revedere» (تا دیدار بعد) به کار می‌رود.',
      en: 'Feminine verbal noun used in the standard formal farewell locution "la revedere".',
    },
  },
  {
    id: 'w-core-scuza',
    lemma: 'scuză',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'scuza',
    plural: 'scuze',
    translations: {
      en: 'excuse / apology',
      fa: 'عذرخواهی / بهانه',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/scuz%C4%83',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'اسم مؤنث که صورت جمع آن «scuze» مستقلاً به عنوان عذرخواهی و معذرت‌خواهی سریع به کار می‌رود.',
      en: 'Feminine noun whose plural form "scuze" is used standalone as a quick apology.',
    },
  },
];

export const CORE_GREETING_PHRASES: RomanianPhrase[] = [
  // --- احوال‌پرسی‌های روزانه و خداحافظی ---
  {
    id: 'p-core-buna-dimineata',
    slug: 'buna-dimineata',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Bună dimineața!',
      en: 'Good morning!',
      fa: 'صبح بخیر!',
    },
    wordIds: ['w-core-buna', 'w-time-dimineata'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune dimineață (DEX \'09)',
      url: 'https://dexonline.ro/definitie/diminea%C8%9B%C4%83',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'احوال‌پرسی رسمی و خنثی هنگام صبح (تا پیش از ظهر). ساختار: صفت مؤنث bună + اسم معرفه مؤنث dimineața.',
      en: 'Standard morning greeting until noon. Structure: feminine adjective bună + definite feminine noun dimineața.',
    },
  },
  {
    id: 'p-core-buna-ziua',
    slug: 'core-buna-ziua',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Bună ziua!',
      en: 'Good day / Hello!',
      fa: 'روز بخیر / سلام (رسمی)!',
    },
    wordIds: ['w-core-buna', 'w-time-zi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune zi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/zi',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'سلام و احوال‌پرسی استاندارد و رسمی در طول روز (در برابر salut/bună که خودمانی هستند). ساختار: صفت مؤنث bună + اسم معرفه مؤنث ziua.',
      en: 'Standard formal greeting during the day (contrasts with informal salut/bună). Structure: feminine adjective bună + definite feminine noun ziua.',
    },
  },
  {
    id: 'p-core-buna-seara',
    slug: 'buna-seara',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Bună seara!',
      en: 'Good evening!',
      fa: 'عصر بخیر!',
    },
    wordIds: ['w-core-buna', 'w-time-seara'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune seară (DEX \'09)',
      url: 'https://dexonline.ro/definitie/sear%C4%83',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'احوال‌پرسی استاندارد در هنگام عصر و غروب. ساختار: صفت مؤنث bună + اسم معرفه مؤنث seara.',
      en: 'Standard evening greeting. Structure: feminine adjective bună + definite feminine noun seara.',
    },
  },
  {
    id: 'p-core-noapte-buna',
    slug: 'noapte-buna',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Noapte bună!',
      en: 'Good night!',
      fa: 'شب بخیر!',
    },
    wordIds: ['w-time-noapte', 'w-core-buna'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune noapte (DEX \'09)',
      url: 'https://dexonline.ro/definitie/noapte',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'خداحافظی هنگام خواب یا اواخر شب. برخلاف bună dimineața/ziua/seara که در آن‌ها صفت پیش از اسم معرفه می‌آید، در noapte bună اسم نکره در ابتدا و صفت پس از آن می‌آید (وارونگی موصوف و صفت). هر چهار اسم مؤنث هستند، لذا در همه از bună استفاده می‌شود.',
      en: 'Bedtime farewell. Unlike bună dimineața/ziua/seara where adjective precedes definite noun, here the indefinite noun precedes the adjective (word order inversion). All four nouns are feminine, hence bună is used in all.',
    },
  },
  {
    id: 'p-core-la-revedere',
    slug: 'core-la-revedere',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'La revedere!',
      en: 'Goodbye!',
      fa: 'خداحافظ (رسمی)!',
    },
    wordIds: ['w-core-revedere'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune revedere (DEX \'09)',
      url: 'https://dexonline.ro/definitie/revedere',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'خداحافظی استاندارد و رسمی (در برابر pa که غیررسمی و خودمانی است). معنای تحت‌اللفظی: تا دیدار دوباره.',
      en: 'Standard formal farewell (contrasts with informal pa). Literal meaning: until seeing each other again.',
    },
  },
  {
    id: 'p-core-pa',
    slug: 'pa',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'informal',
    intendedUse: 'comprehend',
    text: {
      ro: 'Pa!',
      en: 'Bye!',
      fa: 'خداحافظ (خودمانی)!',
    },
    wordIds: ['w-core-pa'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — interjectie pa (DEX \'09)',
      url: 'https://dexonline.ro/definitie/pa',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'خداحافظی کاملاً خودمانی و دوستانه میان دوستان و آشنایان نزدیک (در برابر la revedere که رسمی است).',
      en: 'Informal farewell used among close friends (contrasts with formal la revedere).',
    },
  },
  {
    id: 'p-core-o-zi-buna',
    slug: 'o-zi-buna',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'O zi bună!',
      en: 'Have a good day!',
      fa: 'روز خوبی داشته باشید!',
    },
    wordIds: ['w-time-zi', 'w-core-buna'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune zi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/zi',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'آرزوی حسن ختام هنگام خداحافظی در طول روز. اسم zi نکره است و صفت bună پس از آن آمده است.',
      en: 'Parting wish during daytime. Indefinite noun zi followed by adjective bună.',
    },
  },

  // --- تعارفات و ادب ---
  {
    id: 'p-core-va-rog',
    slug: 'core-va-rog',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Vă rog.',
      en: 'Please.',
      fa: 'خواهش می‌کنم / لطفاً (رسمی).',
    },
    wordIds: ['w-core-va'],
    verbIds: ['v-core-a-ruga'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie ruga (DEX \'09)',
      url: 'https://dexonline.ro/definitie/ruga',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'فرمول ادب رسمی با ضمیر احترامی vă (در برابر te rog خودمانی). ضمیر رسمی dumneavoastră با صیغه‌ی جمع voi مطابقت می‌کند (vă rog = از شما خواهش می‌کنم).',
      en: 'Formal politeness formula with clitic vă (contrasting with informal te rog). Formal dumneavoastră aligns with voi plural verb/clitics.',
    },
  },
  {
    id: 'p-core-te-rog',
    slug: 'te-rog',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'informal',
    intendedUse: 'comprehend',
    text: {
      ro: 'Te rog.',
      en: 'Please.',
      fa: 'خواهش می‌کنم / لطفاً (خودمانی).',
    },
    wordIds: ['w-core-te'],
    verbIds: ['v-core-a-ruga'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie ruga (DEX \'09)',
      url: 'https://dexonline.ro/definitie/ruga',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'فرمول ادب خودمانی برای درخواست از دوستان و افراد صمیمی (در برابر vă rog رسمی).',
      en: 'Informal request formula among close friends (contrasting with formal vă rog).',
    },
  },
  {
    id: 'p-core-va-multumesc',
    slug: 'va-multumesc',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Vă mulțumesc.',
      en: 'Thank you (formal).',
      fa: 'از شما متشکرم (رسمی).',
    },
    wordIds: ['w-core-va'],
    verbIds: ['v-core-a-multumi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma mulțumi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/mul%C8%9Bumi/paradigma',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'تشکر رسمی با ضمیر برایی vă و اول شخص مفرد mulțumesc. برای احترام به شخص مخاطب (dumneavoastră) از vă استفاده می‌شود.',
      en: 'Formal thank you combining clitic vă and first person singular mulțumesc.',
    },
  },
  {
    id: 'p-core-multumim',
    slug: 'multumim',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Mulțumim.',
      en: 'We thank you / Thank you (collective).',
      fa: 'متشکریم / سپاسگزاریم.',
    },
    verbIds: ['v-core-a-multumi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma mulțumi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/mul%C8%9Bumi/paradigma',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'صیغه‌ی اول شخص جمع (ما) از فعل a mulțumi برای تشکر از طرف یک جمع یا خانواده.',
      en: 'First person plural form of a mulțumi used when thanking on behalf of a group.',
    },
  },
  {
    id: 'p-core-cu-placere',
    slug: 'core-cu-placere',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Cu plăcere.',
      en: "You're welcome / With pleasure.",
      fa: 'خواهش می‌کنم / با کمال میل.',
    },
    wordIds: ['w-core-placere'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune plăcere (DEX \'09)',
      url: 'https://dexonline.ro/definitie/pl%C4%83cere',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'پاسخ استاندارد و مؤدبانه به تشکر (Mulțumesc). ترکیب حرف اضافه‌ی cu و اسم plăcere.',
      en: 'Standard polite response to "Mulțumesc". Combines preposition cu and noun plăcere.',
    },
  },
  {
    id: 'p-core-scuze',
    slug: 'scuze',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Scuze.',
      en: 'Sorry / Excuses.',
      fa: 'ببخشید / پوزش.',
    },
    wordIds: ['w-core-scuza'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie scuză (DEX \'09)',
      url: 'https://dexonline.ro/definitie/scuz%C4%83',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'عذرخواهی کوتاه و روزمره با استفاده از صورت جمع اسم scuză.',
      en: 'Short everyday apology using the plural form of the noun scuză.',
    },
  },

  // --- گفتگوهای کوتاه و احوال‌پرسی ---
  {
    id: 'p-core-ce-mai-faceti',
    slug: 'ce-mai-faceti',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Ce mai faceți?',
      en: 'How are you? (formal/plural)',
      fa: 'حال شما چطور است؟ / چه خبر؟ (رسمی)',
    },
    wordIds: ['w-core-ce', 'w-core-mai-adv'],
    verbIds: ['v-core-a-face'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie face (DEX \'09)',
      url: 'https://dexonline.ro/definitie/face',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'احوال‌پرسی رسمی یا خطاب به چند نفر با صیغه‌ی دوم‌شخص جمع faceți از فعل a face. ضمیر احترامی dumneavoastră نیز همواره فعل جمع می‌گیرد. در برابر Ce mai faci? خودمانی.',
      en: 'Formal greeting or addressed to multiple people using second-person plural faceți of a face. Formal dumneavoastră always takes plural verb. Contrasts with informal Ce mai faci?.',
    },
  },
  {
    id: 'p-core-ce-mai-faci',
    slug: 'ce-mai-faci',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'informal',
    intendedUse: 'comprehend',
    text: {
      ro: 'Ce mai faci?',
      en: 'How are you? (informal)',
      fa: 'حالت چطوره؟ / چه خبر؟ (خودمانی)',
    },
    wordIds: ['w-core-ce', 'w-core-mai-adv'],
    verbIds: ['v-core-a-face'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie face (DEX \'09)',
      url: 'https://dexonline.ro/definitie/face',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'احوال‌پرسی غیررسمی و صمیمانه با صیغه‌ی دوم‌شخص مفرد faci (در برابر Ce mai faceți? رسمی). قید mai در اینجا نقش احوال‌پرسی دارد.',
      en: 'Informal friendly greeting using second-person singular faci (contrasts with formal Ce mai faceți?). Adverb mai functions as greeting marker.',
    },
  },
  {
    id: 'p-core-bine-multumesc',
    slug: 'bine-multumesc',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Bine, mulțumesc.',
      en: 'Fine, thank you.',
      fa: 'خوبم، ممنون.',
    },
    wordIds: ['w-core-bine'],
    verbIds: ['v-core-a-multumi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie bine / mulțumi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/bine',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'پاسخ متداول و مؤدبانه به احوال‌پرسی‌های Ce mai faci? و Ce mai faceți?. ترکیب قید bine و صیغه‌ی اول شخص mulțumesc.',
      en: 'Standard polite response to greeting inquiries Ce mai faci? and Ce mai faceți?. Combines adverb bine and verb mulțumesc.',
    },
  },
  {
    id: 'p-core-cum-va-numiti',
    slug: 'cum-va-numiti',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Cum vă numiți?',
      en: 'What is your name? (formal)',
      fa: 'نام شما چیست؟ (رسمی)',
    },
    wordIds: ['w-core-cum', 'w-core-va'],
    verbIds: ['v-core-a-numi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma numi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/numi/paradigma',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'پرسش رسمی درباره‌ی نام با ضمیر vă و صیغه‌ی دوم‌شخص جمع numiți از فعل a numi. ضمیر احترامی dumneavoastră صیغه‌ی جمع می‌گیرد، حتی وقتی با یک نفر حرف می‌زنید.',
      en: "Formal inquiry about one's name, using vă and the 2nd person plural numiți of a numi. Polite dumneavoastră governs plural agreement even when addressing one person.",
    },
  },
  {
    id: 'p-core-ma-numesc',
    slug: 'core-ma-numesc',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Mă numesc {{name}}.',
      en: 'My name is {{name}}.',
      fa: 'نام من {{name}} است.',
    },
    wordIds: ['w-core-ma'],
    verbIds: ['v-core-a-numi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma numi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/numi/paradigma',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'فرمول استاندارد و مؤدبانه برای معرفی نام خود با ضمیر انعکاسی mă و صیغه‌ی اول‌شخص مفرد numesc از فعل a numi.',
      en: 'Standard polite formula for self-introduction with reflexive mă and first-person numesc of a numi.',
    },
  },
  {
    id: 'p-core-imi-pare-bine',
    slug: 'imi-pare-bine',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Îmi pare bine.',
      en: 'Pleased to meet you / Glad.',
      fa: 'خوش‌وقتم / خوشحالم.',
    },
    wordIds: ['w-core-imi', 'w-core-bine'],
    verbIds: ['v-core-a-parea'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie părea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/p%C4%83rea',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'عبارت رایج هنگام آشنایی و معرفی به معنای «خوش‌وقتم». ساختار: ضمیر برایی îmi + فعل سوم‌شخص pare + قید bine (ذیل مدخل părea در فرهنگ لغت).',
      en: 'Common expression upon meeting someone meaning "pleased to meet you". Structure: dative clitic îmi + 3rd person pare + adverb bine (cited directly under părea in DEX).',
    },
  },
  {
    id: 'p-core-imi-pare-rau',
    slug: 'core-imi-pare-rau',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Îmi pare rău.',
      en: "I'm sorry.",
      fa: 'متأسفم.',
    },
    wordIds: ['w-core-imi', 'w-core-rau'],
    verbIds: ['v-core-a-parea'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie părea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/p%C4%83rea',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    isFree: true,
    usageNote: {
      fa: 'فرمول استاندارد برای ابراز تأسف و همدردی. ساختار: ضمیر برایی îmi + فعل سوم‌شخص pare + قید rău (عیناً ذیل مدخل părea در فرهنگ لغت نقل شده است).',
      en: 'Standard formula for expressing regret or sympathy. Structure: dative clitic îmi + 3rd person pare + adverb rău (cited directly under părea in DEX).',
    },
  },
];
