import { RomanianWord } from '@/lib/romanian/types';

/**
 * ماژول اعداد هسته‌ی زبان رومانیایی (dre-p163)
 * ایستگاه ۳ از حوزه‌ی core
 *
 * ساختار ماژول:
 * ۱. گروه ۱: اعداد اصلی بدون تغییر جنسیت (۲۵ قلم)
 * ۲. گروه ۲: اعداد دارای صورت‌های مذکر و مؤنث (unu/una, doi/două, doisprezece/douăsprezece) همراه با formOf
 * ۳. گروه ۳: اعداد چندواژه‌ای و اسمی (o sută, o mie)
 * ۴. گروه ۴: اعداد ترتیبی اول تا دهم (primul/prima تا al zecelea/a zecea) + întâi/întâia، همراه با formOf برای صورت‌های مؤنث
 *
 * تمامی اقلام:
 * - status: 'draft'
 * - domains: ['core']
 * - stationId: 'core-numbers'
 * - pos: 'numeral'
 * - intendedUse: 'produce'
 * - منابع معتبر و لینک‌های اثبات‌شده از dexonline
 */

export const CORE_NUMBERS: RomanianWord[] = [
  // =========================================================================
  // گروه ۱: اعداد بدون تغییر جنسیت (Invariable Cardinals)
  // =========================================================================
  {
    id: 'w-num-zero',
    lemma: 'zero',
    pos: 'numeral',
    translations: { en: 'zero', fa: 'صفر' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/zero',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-trei',
    lemma: 'trei',
    pos: 'numeral',
    translations: { en: 'three', fa: 'سه' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/trei',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-patru',
    lemma: 'patru',
    pos: 'numeral',
    translations: { en: 'four', fa: 'چهار' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/patru',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-cinci',
    lemma: 'cinci',
    pos: 'numeral',
    translations: { en: 'five', fa: 'پنج' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/cinci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-sase',
    lemma: 'șase',
    pos: 'numeral',
    translations: { en: 'six', fa: 'شش' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/%C8%99ase',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-sapte',
    lemma: 'șapte',
    pos: 'numeral',
    translations: { en: 'seven', fa: 'هفت' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/%C8%99apte',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-opt',
    lemma: 'opt',
    pos: 'numeral',
    translations: { en: 'eight', fa: 'هشت' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/opt',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-noua',
    lemma: 'nouă',
    pos: 'numeral',
    translations: { en: 'nine', fa: 'نه' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/nou%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'واژه‌ی nouă دارای ۳ کاربرد کاملاً متمایز است: ۱) عدد ۹ («nouă bani»)، ۲) صفت مفرد مؤنث به معنای «نو/جدید» («casă nouă»)، ۳) ضمیر برایی تأکیدی به معنای «به ما» («ne dă nouă»).',
      en: 'The word "nouă" has 3 distinct roles: 1) cardinal number 9, 2) feminine singular adjective meaning "new", 3) tonic dative pronoun meaning "to us".',
    },
  },
  {
    id: 'w-num-zece',
    lemma: 'zece',
    pos: 'numeral',
    translations: { en: 'ten', fa: 'ده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/zece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-unsprezece',
    lemma: 'unsprezece',
    pos: 'numeral',
    translations: { en: 'eleven', fa: 'یازده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/unsprezece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-treisprezece',
    lemma: 'treisprezece',
    pos: 'numeral',
    translations: { en: 'thirteen', fa: 'سیزده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/treisprezece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-paisprezece',
    lemma: 'paisprezece',
    pos: 'numeral',
    translations: { en: 'fourteen', fa: 'چهارده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/paisprezece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'املای استاندارد این عدد paisprezece است (نه patrusprezece).',
      en: 'The standard spelling is "paisprezece" (not "patrusprezece").',
    },
  },
  {
    id: 'w-num-cincisprezece',
    lemma: 'cincisprezece',
    pos: 'numeral',
    translations: { en: 'fifteen', fa: 'پانزده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/cincisprezece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-saisprezece',
    lemma: 'șaisprezece',
    pos: 'numeral',
    translations: { en: 'sixteen', fa: 'شانزده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/%C8%99aisprezece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'املای استاندارد این عدد șaisprezece است (نه șasesprezece).',
      en: 'The standard spelling is "șaisprezece" (not "șasesprezece").',
    },
  },
  {
    id: 'w-num-saptesprezece',
    lemma: 'șaptesprezece',
    pos: 'numeral',
    translations: { en: 'seventeen', fa: 'هفده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/%C8%99aptesprezece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-optsprezece',
    lemma: 'optsprezece',
    pos: 'numeral',
    translations: { en: 'eighteen', fa: 'هجده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/optsprezece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-nouasprezece',
    lemma: 'nouăsprezece',
    pos: 'numeral',
    translations: { en: 'nineteen', fa: 'نوزده' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/nou%C4%83sprezece',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'تا عدد نوزده، اسم مستقیماً پس از عدد می‌آید و نیازی به حرف اضافه نیست: «nouăsprezece bani». از عدد ۲۰ به بعد حرف اضافه‌ی de لازم است.',
      en: 'Up to 19, the noun follows the numeral directly without "de": "nouăsprezece bani".',
    },
  },
  {
    id: 'w-num-douazeci',
    lemma: 'douăzeci',
    pos: 'numeral',
    translations: { en: 'twenty', fa: 'بیست' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/dou%C4%83zeci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قاعده‌ی de بعد از ۲۰: از عدد ۲۰ به بالا، هنگام شمارش اسم، حرف اضافه‌ی de بین عدد و اسم قرار می‌گیرد: «douăzeci de bani» (در مقایسه با «nouăsprezece bani»). در اعداد مرکب نیز اگر به عدد ۱ یا ۲ ختم شود حرف de نمی‌آید، اما در سایر مضارب ۲۰ de اجباری است.',
      en: 'Preposition "de" rule: from 20 onwards, "de" is placed between the numeral and the noun: "douăzeci de bani".',
    },
  },
  {
    id: 'w-num-treizeci',
    lemma: 'treizeci',
    pos: 'numeral',
    translations: { en: 'thirty', fa: 'سی' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/treizeci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'در اعداد مرکب، بین دهگان و یکان حرف ربط și اجباری است: «treizeci și cinci» (۳۵) یا «douăzeci și unu» (۲۱). عدم استفاده از și غلط است.',
      en: 'Compound numbers require the conjunction "și" between tens and units: "treizeci și cinci" (35).',
    },
  },
  {
    id: 'w-num-patruzeci',
    lemma: 'patruzeci',
    pos: 'numeral',
    translations: { en: 'forty', fa: 'چهل' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/patruzeci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-cincizeci',
    lemma: 'cincizeci',
    pos: 'numeral',
    translations: { en: 'fifty', fa: 'پنجاه' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/cincizeci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-saizeci',
    lemma: 'șaizeci',
    pos: 'numeral',
    translations: { en: 'sixty', fa: 'شصت' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/%C8%99aizeci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'املای استاندارد عدد ۶۰ در رومانیایی șaizeci است (نه șasezeci).',
      en: 'The standard spelling is "șaizeci" (not "șasezeci").',
    },
  },
  {
    id: 'w-num-saptezeci',
    lemma: 'șaptezeci',
    pos: 'numeral',
    translations: { en: 'seventy', fa: 'هفتاد' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/%C8%99aptezeci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-optzeci',
    lemma: 'optzeci',
    pos: 'numeral',
    translations: { en: 'eighty', fa: 'هشتاد' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/optzeci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-nouazeci',
    lemma: 'nouăzeci',
    pos: 'numeral',
    translations: { en: 'ninety', fa: 'نود' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/nou%C4%83zeci',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },

  // =========================================================================
  // گروه ۲: اعداد با تغییر جنسیت (Gender-varying Cardinals)
  // =========================================================================
  {
    id: 'w-num-unu',
    lemma: 'unu',
    pos: 'numeral',
    translations: { en: 'one (masculine/neuter)', fa: 'یک (مذکر/خنثی)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma (P105)',
      url: 'https://dexonline.ro/definitie/unu/paradigma',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'عدد یک با جنسیت اسم بعدش مطابقت می‌گیرد: برای اسم مذکر و خنثی «un ban» و برای اسم مؤنث «o casă». هنگام شمارش مجرد یا بدون اسم از صورت unu (مذکر) یا una (مؤنث) استفاده می‌شود.',
      en: 'The number 1 agrees with the noun gender: "un ban" (m) / "o casă" (f). Standalone forms are "unu" and "una".',
    },
  },
  {
    id: 'w-num-una',
    lemma: 'una',
    pos: 'numeral',
    formOf: 'w-num-unu',
    translations: { en: 'one (feminine)', fa: 'یک (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma (P105)',
      url: 'https://dexonline.ro/definitie/unu/paradigma',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-doi',
    lemma: 'doi',
    pos: 'numeral',
    translations: { en: 'two (masculine)', fa: 'دو (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma (P43)',
      url: 'https://dexonline.ro/definitie/doi/paradigma',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'عدد دو با جنسیت اسم بعدش مطابقت می‌گیرد: برای اسم مذکر «doi bani» و برای اسم مؤنث یا خنثی جمع «două case». در تاریخ‌ها، از روز دوم به بعد از عدد اصلی استفاده می‌شود (مانند «doi»)، نه عدد ترتیبی («al doilea»).',
      en: 'The number 2 agrees in gender: "doi bani" (m) vs "două case" (f). For dates after the 1st, cardinal numbers are used (e.g. "doi", not "al doilea").',
    },
  },
  {
    id: 'w-num-doua',
    lemma: 'două',
    pos: 'numeral',
    formOf: 'w-num-doi',
    translations: { en: 'two (feminine/neuter)', fa: 'دو (مؤنث/خنثی)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma (P43)',
      url: 'https://dexonline.ro/definitie/doi/paradigma',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-doisprezece',
    lemma: 'doisprezece',
    pos: 'numeral',
    translations: { en: 'twelve (masculine)', fa: 'دوازده (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma (P45)',
      url: 'https://dexonline.ro/definitie/doisprezece/paradigma',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'عدد ۱۲ نیز مانند ۲ با جنسیت اسم بعدش مطابقت دارد: «doisprezece bani» (مذکر) در برابر «douăsprezece case» (مؤنث/خنثی).',
      en: 'The number 12 agrees in gender: "doisprezece bani" (m) vs "douăsprezece case" (f).',
    },
  },
  {
    id: 'w-num-douasprezece',
    lemma: 'douăsprezece',
    pos: 'numeral',
    formOf: 'w-num-doisprezece',
    translations: { en: 'twelve (feminine/neuter)', fa: 'دوازده (مؤنث/خنثی)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma (P45)',
      url: 'https://dexonline.ro/definitie/doisprezece/paradigma',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },

  // =========================================================================
  // گروه ۳: چندواژه‌ای و اسمی (Multi-word / Noun Expressions)
  // =========================================================================
  {
    id: 'w-num-o-suta',
    lemma: 'o sută',
    pos: 'numeral',
    translations: { en: 'one hundred', fa: 'صد، یکصد' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie sută (DEX \'09)',
      url: 'https://dexonline.ro/definitie/sut%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'واژه‌ی sută از نظر دستوری اسمی مؤنث است و با حرف تعریف نامعین o ترکیب شده و «o sută» را می‌سازد.',
      en: 'The word "sută" is grammatically a feminine noun used with indefinite article "o" to form "o sută" (100).',
    },
  },
  {
    id: 'w-num-o-mie',
    lemma: 'o mie',
    pos: 'numeral',
    translations: { en: 'one thousand', fa: 'هزار، یک هزار' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie mie (DEX \'09)',
      url: 'https://dexonline.ro/definitie/mie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'واژه‌ی mie اسمی مؤنث است و به همراه حرف تعریف نامعین o صورت «o mie» را تشکیل می‌دهد.',
      en: 'The word "mie" is grammatically a feminine noun used with indefinite article "o" to form "o mie" (1000).',
    },
  },

  // =========================================================================
  // گروه ۴: ترتیبی‌ها، یک تا ده + întâi/întâia (Ordinals)
  // =========================================================================
  {
    id: 'w-num-primul',
    lemma: 'primul',
    pos: 'numeral',
    translations: { en: 'the first (masculine)', fa: 'اول، نخست (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie prim (DOOM 3 / DEX \'09)',
      url: 'https://dexonline.ro/definitie/prim',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-prima',
    lemma: 'prima',
    pos: 'numeral',
    formOf: 'w-num-primul',
    translations: { en: 'the first (feminine)', fa: 'اول، نخست (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie prim (DOOM 3 / DEX \'09)',
      url: 'https://dexonline.ro/definitie/prim',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-doilea',
    lemma: 'al doilea',
    pos: 'numeral',
    translations: { en: 'the second (masculine)', fa: 'دوم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie doilea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/doilea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-doua',
    lemma: 'a doua',
    pos: 'numeral',
    formOf: 'w-num-al-doilea',
    translations: { en: 'the second (feminine)', fa: 'دوم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie doilea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/doilea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-treilea',
    lemma: 'al treilea',
    pos: 'numeral',
    translations: { en: 'the third (masculine)', fa: 'سوم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie treilea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/treilea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-treia',
    lemma: 'a treia',
    pos: 'numeral',
    formOf: 'w-num-al-treilea',
    translations: { en: 'the third (feminine)', fa: 'سوم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie treilea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/treilea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-patrulea',
    lemma: 'al patrulea',
    pos: 'numeral',
    translations: { en: 'the fourth (masculine)', fa: 'چهارم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie patrulea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/patrulea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-patra',
    lemma: 'a patra',
    pos: 'numeral',
    formOf: 'w-num-al-patrulea',
    translations: { en: 'the fourth (feminine)', fa: 'چهارم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie patrulea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/patrulea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-cincilea',
    lemma: 'al cincilea',
    pos: 'numeral',
    translations: { en: 'the fifth (masculine)', fa: 'پنجم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie cincilea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/cincilea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-cincea',
    lemma: 'a cincea',
    pos: 'numeral',
    formOf: 'w-num-al-cincilea',
    translations: { en: 'the fifth (feminine)', fa: 'پنجم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie cincilea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/cincilea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-saselea',
    lemma: 'al șaselea',
    pos: 'numeral',
    translations: { en: 'the sixth (masculine)', fa: 'ششم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie șaselea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/%C8%99aselea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-sasea',
    lemma: 'a șasea',
    pos: 'numeral',
    formOf: 'w-num-al-saselea',
    translations: { en: 'the sixth (feminine)', fa: 'ششم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie șaselea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/%C8%99aselea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-saptelea',
    lemma: 'al șaptelea',
    pos: 'numeral',
    translations: { en: 'the seventh (masculine)', fa: 'هفتم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie șaptelea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/%C8%99aptelea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-saptea',
    lemma: 'a șaptea',
    pos: 'numeral',
    formOf: 'w-num-al-saptelea',
    translations: { en: 'the seventh (feminine)', fa: 'هفتم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie șaptelea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/%C8%99aptelea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-optulea',
    lemma: 'al optulea',
    pos: 'numeral',
    translations: { en: 'the eighth (masculine)', fa: 'هشتم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie optulea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/optulea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-opta',
    lemma: 'a opta',
    pos: 'numeral',
    formOf: 'w-num-al-optulea',
    translations: { en: 'the eighth (feminine)', fa: 'هشتم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie optulea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/optulea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-noualea',
    lemma: 'al nouălea',
    pos: 'numeral',
    translations: { en: 'the ninth (masculine)', fa: 'نهم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie nouălea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/nou%C4%83lea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-noua',
    lemma: 'a noua',
    pos: 'numeral',
    formOf: 'w-num-al-noualea',
    translations: { en: 'the ninth (feminine)', fa: 'نهم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie nouălea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/nou%C4%83lea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-al-zecelea',
    lemma: 'al zecelea',
    pos: 'numeral',
    translations: { en: 'the tenth (masculine)', fa: 'دهم (مذکر)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie zecelea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/zecelea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-a-zecea',
    lemma: 'a zecea',
    pos: 'numeral',
    formOf: 'w-num-al-zecelea',
    translations: { en: 'the tenth (feminine)', fa: 'دهم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie zecelea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/zecelea',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
  {
    id: 'w-num-intai',
    lemma: 'întâi',
    pos: 'numeral',
    translations: { en: 'first (ordinal / dates)', fa: 'اول، یکم (روز اول ماه / ترتیبی)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie (DOOM 3)',
      url: 'https://dexonline.ro/definitie/%C3%AEnt%C3%A2i',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'در بیان تاریخ‌ها، برای روز اول همیشه از صورت ترتیبی întâi استفاده می‌شود. از روز دوم به بعد، برخلاف زبان‌های دیگر، از عدد اصلی مانند doi (نه al doilea) استفاده می‌شود.',
      en: 'In calendar dates, "întâi" is used exclusively for the 1st of the month. From the 2nd onwards, cardinal numbers are used (e.g. "doi", not "al doilea").',
    },
  },
  {
    id: 'w-num-intaia',
    lemma: 'întâia',
    pos: 'numeral',
    formOf: 'w-num-intai',
    translations: { en: 'first (feminine ordinal)', fa: 'اول، یکم (مؤنث)' },
    domains: ['core'],
    stationId: 'core-numbers',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie întâi (DOOM 3)',
      url: 'https://dexonline.ro/definitie/%C3%AEnt%C3%A2i',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
  },
];
