import { RomanianWord, RomanianPhrase } from '@/lib/romanian/types';

/**
 * ماژول احوال‌پرسی و ادب هسته‌ی رومانیایی (dre-p166)
 * ایستگاه ۵ از حوزه‌ی core
 *
 * شامل:
 * - ۱۲ واژه (bon/bună, bine, rău, mai [adv], salut [noun], pa [interj], da, nu, plăcere, revedere, scuză)
 * - ۲۰ عبارت کاربردی با منبع‌دهی دقیق
 * - ثبت سیاست رجیستر روی چهار جفت تعاملی (dumneavoastră فعل جمع voi می‌گیرد)
 * - قاعده وارونگی در noapte bună
 *
 * تمامی اقلام با status: 'published' و stationId: 'core-greetings' ثبت شده‌اند.
 */

export const CORE_GREETING_WORDS: RomanianWord[] = [
  {
    id: 'w-core-bun',
    lemma: 'bun',
    pos: 'adj',
    translations: {
      en: 'good (masculine)',
      fa: 'خوب (مذکر)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-7-the-words',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/bun',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'صفت پایه با معنای «خوب». صورت مؤنث مفرد آن «' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: '» در بیشتر احوال‌پرسی‌های روزانه به کار می‌رود.' },
      ],
      en: [
        { t: 'Base adjective meaning ' },
      ],
    },
  },
  {
    id: 'w-core-buna',
    lemma: 'bună',
    pos: 'adj',
    formOf: 'w-core-bun',
    translations: {
      en: 'good (feminine)',
      fa: 'خوب (مؤنث)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-7-the-words',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/bun',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'صورت مؤنث مفرد صفت ' },
        { ref: 'w-core-bun', display: 'bun' },
        { t: '. در احوال‌پرسی‌ها پیش یا پس از اسم مؤنث می‌آید: ' },
        { ref: 'p-core-buna-dimineata', display: 'bună dimineața' },
        { t: '، ' },
        { ref: 'p-core-buna-ziua', display: 'bună ziua' },
        { t: '، ' },
        { ref: 'p-core-buna-seara', display: 'bună seara' },
        { t: '، ' },
        { ref: 'p-core-noapte-buna', display: 'noapte bună' },
        { t: '.' },
      ],
      en: [
        { t: 'Feminine singular of ' },
        { ref: 'w-core-bun', display: 'bun' },
        { t: '. Used in greetings before or after feminine nouns.' },
      ],
    },
  },
  {
    id: 'w-core-bine',
    lemma: 'bine',
    pos: 'adv',
    translations: {
      en: 'well / fine',
      fa: 'خوب / به خوبی',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-5-how-are-you',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/bine',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'قید حالت با کاربرد فراوان در پاسخ‌های احوال‌پرسی («' },
        { ref: 'p-core-bine-multumesc', display: 'Bine, mulțumesc' },
        { t: '») و تعارفات («' },
        { ref: 'p-core-imi-pare-bine', display: 'Îmi pare bine' },
        { t: '»).' },
      ],
      en: [
        { t: 'Adverb widely used in greeting responses (' },
      ],
    },
  },
  {
    id: 'w-core-rau',
    lemma: 'rău',
    pos: 'adv',
    translations: {
      en: 'bad / badly / sorry',
      fa: 'بد / ناراحت',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-7-the-words',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/r%C4%83u',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'قید منفی که در ترکیب با فعل ' },
        { ref: 'v-core-a-parea', display: 'părea' },
        { t: ' عبارت عذرخواهی و تأسف «' },
        { ref: 'p-core-imi-pare-rau', display: 'Îmi pare rău' },
        { t: '» (متأسفم) را می‌سازد.' },
      ],
      en: [
        { t: 'Adverb used with verb ' },
        { ref: 'v-core-a-parea', display: 'părea' },
        { t: ' in the expression of apology and sympathy ' },
      ],
    },
  },
  {
    id: 'w-core-mai-adv',
    lemma: 'mai',
    pos: 'adv',
    translations: {
      en: 'more / else (in greetings: Ce mai faci?)',
      fa: 'دیگر / بیشتر (در احوال‌پرسی: چه خبر)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-7-the-words',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/mai',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'قید احوال‌پرسی و تفضیلی در عبارت‌هایی چون ' },
        { ref: 'p-core-ce-mai-faci', display: 'Ce mai faci' },
        { t: '?. همنگاشت با نام ماه مه، ولی واژه‌ی مستقلی است و رابطه‌ی صرفی با آن ندارد.' },
      ],
      en: [
        { t: 'Greeting and comparative adverb used in phrases like ' },
        { ref: 'p-core-ce-mai-faci', display: 'Ce mai faci' },
        { t: '?. Homograph of the month May, but an independent word with no inflectional relation.' },
      ],
    },
  },
  {
    id: 'w-core-salut',
    lemma: 'salut',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'salutul',
    plural: 'saluturi',
    translations: {
      en: 'greeting / hello',
      fa: 'درود / سلام (غیررسمی)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-7-the-words',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/salut',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'اسم خنثی (' },
        { ref: 'w-core-salut', display: 'salutul' },
        { t: ' / ' },
        { ref: 'w-core-salut', display: 'saluturi' },
        { t: ') که طبق تعریف فرهنگ لغت به صورت ندایی به عنوان سلام و درود غیررسمی (' },
        { ref: 'w-core-salut', display: 'Salut' },
        { t: '!) نیز به کار می‌رود.' },
      ],
      en: [
        { t: 'Neuter noun (' },
        { ref: 'w-core-salut', display: 'salutul' },
        { t: ' / ' },
        { ref: 'w-core-salut', display: 'saluturi' },
        { t: ') used as an informal greeting (' },
        { ref: 'w-core-salut', display: 'Salut' },
        { t: '!) per dictionary definition.' },
      ],
    },
  },
  {
    id: 'w-core-pa',
    lemma: 'pa',
    pos: 'interj',
    translations: {
      en: 'bye',
      fa: 'خداحافظ (خودمانی)',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-7-the-words',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09 / DOOM 3)',
      url: 'https://dexonline.ro/definitie/pa',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'صوت خداحافظی غیررسمی و صمیمانه میان دوستان و آشنایان نزدیک.' },
      ],
      en: [
        { t: 'Informal farewell greeting among friends and close acquaintances.' },
      ],
    },
  },
  {
    id: 'w-core-da',
    lemma: 'da',
    pos: 'adv',
    translations: {
      en: 'yes',
      fa: 'بله / آره',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-2-yes-no-bye',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/da',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
  },
  {
    id: 'w-core-nu',
    lemma: 'nu',
    pos: 'adv',
    translations: {
      en: 'no / not',
      fa: 'نه / خیر',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-2-yes-no-bye',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/nu',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
  },
  {
    id: 'w-core-placere',
    lemma: 'plăcere',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'plăcerea',
    plural: 'plăceri',
    translations: {
      en: 'pleasure',
      fa: 'لذت / خوشوقتی',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-6-introduce',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/pl%C4%83cere',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'اسم مؤنث که در لوکوسیون «' },
        { ref: 'p-core-cu-placere', display: 'cu plăcere' },
        { t: '» (خواهش می‌کنم / با کمال میل) به کار می‌رود.' },
      ],
      en: [
        { t: 'Feminine noun used in the locution ' },
      ],
    },
  },
  {
    id: 'w-core-revedere',
    lemma: 'revedere',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'revederea',
    plural: 'revederi',
    translations: {
      en: 'seeing again / meeting again',
      fa: 'دیدار دوباره',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-7-the-words',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/revedere',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'اسم مؤنث با ریشه‌ی فعلی که در لوکوسیون خداحافظی رسمی «' },
        { ref: 'p-core-la-revedere', display: 'la revedere' },
        { t: '» (تا دیدار بعد) به کار می‌رود.' },
      ],
      en: [
        { t: 'Feminine verbal noun used in the standard formal farewell locution ' },
      ],
    },
  },
  {
    id: 'w-core-scuza',
    lemma: 'scuză',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'scuza',
    plural: 'scuze',
    translations: {
      en: 'excuse / apology',
      fa: 'عذرخواهی / بهانه',
    },
    domains: ['core'],
    stationId: 'core-greetings',
    stepId: 'greet-4-apology',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX \'09)',
      url: 'https://dexonline.ro/definitie/scuz%C4%83',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    usageNote: {
      fa: [
        { t: 'اسم مؤنث که صورت جمع آن «' },
        { ref: 'w-core-scuza', display: 'scuze' },
        { t: '» مستقلاً به عنوان عذرخواهی و معذرت‌خواهی سریع به کار می‌رود.' },
      ],
      en: [
        { t: 'Feminine noun whose plural form ' },
      ],
    },
  },
];

export const CORE_GREETING_PHRASES: RomanianPhrase[] = [
  // --- احوال‌پرسی‌های روزانه و خداحافظی ---
  {
    id: 'p-core-buna-dimineata',
    slug: 'buna-dimineata',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-1-hello',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Bună dimineața!',
      en: 'Good morning!',
      fa: 'صبح بخیر!',
    },
    wordIds: ['w-core-buna', 'w-time-dimineata'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune dimineață (DEX \'09)',
      url: 'https://dexonline.ro/definitie/diminea%C8%9B%C4%83',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'ترکیب ثابت احوال‌پرسی؛ اسم dimineață در ایستگاه زمان تحلیل می‌شود',
      analysedAt: ['core-time'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'احوال‌پرسی رسمی و خنثی هنگام صبح (تا پیش از ظهر). ساختار: صفت مؤنث ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' + اسم معرفه مؤنث ' },
        { ref: 'w-time-dimineata', display: 'dimineața' },
        { t: '.' },
      ],
      en: [
        { t: 'Standard morning greeting until noon. Structure: feminine adjective ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' + definite feminine noun ' },
        { ref: 'w-time-dimineata', display: 'dimineața' },
        { t: '.' },
      ],
    },
  },
  {
    id: 'p-core-buna-ziua',
    slug: 'core-buna-ziua',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-1-hello',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Bună ziua!',
      en: 'Good day / Hello!',
      fa: 'روز بخیر / سلام (رسمی)!',
    },
    wordIds: ['w-core-buna', 'w-time-zi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune zi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/zi',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'ترکیب ثابت احوال‌پرسی؛ اسم zi و صورت معرفه‌اش در ایستگاه زمان تحلیل می‌شود',
      analysedAt: ['core-time'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'سلام و احوال‌پرسی استاندارد و رسمی در طول روز (در برابر ' },
        { ref: 'w-core-salut', display: 'salut' },
        { t: '/' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' که خودمانی هستند). ساختار: صفت مؤنث ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' + اسم معرفه مؤنث ' },
        { ref: 'w-time-zi', display: 'ziua' },
        { t: '.' },
      ],
      en: [
        { t: 'Standard formal greeting during the day (contrasts with informal ' },
        { ref: 'w-core-salut', display: 'salut' },
        { t: '/' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: '). Structure: feminine adjective ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' + definite feminine noun ' },
        { ref: 'w-time-zi', display: 'ziua' },
        { t: '.' },
      ],
    },
  },
  {
    id: 'p-core-buna-seara',
    slug: 'buna-seara',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-1-hello',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Bună seara!',
      en: 'Good evening!',
      fa: 'عصر بخیر!',
    },
    wordIds: ['w-core-buna', 'w-time-seara'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune seară (DEX \'09)',
      url: 'https://dexonline.ro/definitie/sear%C4%83',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'ترکیب ثابت احوال‌پرسی؛ اسم seară در ایستگاه زمان تحلیل می‌شود',
      analysedAt: ['core-time'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'احوال‌پرسی استاندارد در هنگام عصر و غروب. ساختار: صفت مؤنث ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' + اسم معرفه مؤنث ' },
        { ref: 'w-time-seara', display: 'seara' },
        { t: '.' },
      ],
      en: [
        { t: 'Standard evening greeting. Structure: feminine adjective ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' + definite feminine noun ' },
        { ref: 'w-time-seara', display: 'seara' },
        { t: '.' },
      ],
    },
  },
  {
    id: 'p-core-noapte-buna',
    slug: 'noapte-buna',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-1-hello',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Noapte bună!',
      en: 'Good night!',
      fa: 'شب بخیر!',
    },
    wordIds: ['w-time-noapte', 'w-core-buna'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune noapte (DEX \'09)',
      url: 'https://dexonline.ro/definitie/noapte',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'ترکیب ثابت شب‌بخیر؛ اسم noapte در ایستگاه زمان تحلیل می‌شود',
      analysedAt: ['core-time'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'خداحافظی هنگام خواب یا اواخر شب. برخلاف ' },
        { ref: 'p-core-buna-dimineata', display: 'bună dimineața' },
        { t: '/' },
        { ref: 'w-time-zi', display: 'ziua' },
        { t: '/' },
        { ref: 'w-time-seara', display: 'seara' },
        { t: ' که در آن‌ها صفت پیش از اسم معرفه می‌آید، در ' },
        { ref: 'p-core-noapte-buna', display: 'noapte bună' },
        { t: ' اسم نکره در ابتدا و صفت پس از آن می‌آید (وارونگی موصوف و صفت). هر چهار اسم مؤنث هستند، لذا در همه از ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' استفاده می‌شود.' },
      ],
      en: [
        { t: 'Bedtime farewell. Unlike ' },
        { ref: 'p-core-buna-dimineata', display: 'bună dimineața' },
        { t: '/' },
        { ref: 'w-time-zi', display: 'ziua' },
        { t: '/' },
        { ref: 'w-time-seara', display: 'seara' },
        { t: ' where adjective precedes definite noun, here the indefinite noun precedes the adjective (word order inversion). All four nouns are feminine, hence ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' is used in all.' },
      ],
    },
  },
  {
    id: 'p-core-la-revedere',
    slug: 'core-la-revedere',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-2-yes-no-bye',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'La revedere!',
      en: 'Goodbye!',
      fa: 'خداحافظ (رسمی)!',
    },
    wordIds: ['w-core-revedere'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune revedere (DEX \'09)',
      url: 'https://dexonline.ro/definitie/revedere',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'خداحافظی استاندارد و رسمی (در برابر ' },
        { ref: 'w-core-pa', display: 'pa' },
        { t: ' که غیررسمی و خودمانی است). معنای تحت‌اللفظی: تا دیدار دوباره.' },
      ],
      en: [
        { t: 'Standard formal farewell (contrasts with informal ' },
        { ref: 'w-core-pa', display: 'pa' },
        { t: '). Literal meaning: until seeing each other again.' },
      ],
    },
  },
  {
    id: 'p-core-pa',
    slug: 'pa',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-2-yes-no-bye',
    level: 'beginner',
    register: 'informal',
    intendedUse: 'comprehend',
    text: {
      ro: 'Pa!',
      en: 'Bye!',
      fa: 'خداحافظ (خودمانی)!',
    },
    wordIds: ['w-core-pa'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — interjectie pa (DEX \'09)',
      url: 'https://dexonline.ro/definitie/pa',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'خداحافظی کاملاً خودمانی و دوستانه میان دوستان و آشنایان نزدیک (در برابر ' },
        { ref: 'p-core-la-revedere', display: 'la revedere' },
        { t: ' که رسمی است).' },
      ],
      en: [
        { t: 'Informal farewell used among close friends (contrasts with formal ' },
        { ref: 'p-core-la-revedere', display: 'la revedere' },
        { t: ').' },
      ],
    },
  },
  {
    id: 'p-core-o-zi-buna',
    slug: 'o-zi-buna',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-1-hello',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'O zi bună!',
      en: 'Have a good day!',
      fa: 'روز خوبی داشته باشید!',
    },
    wordIds: ['w-time-zi', 'w-core-buna'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune zi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/zi',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'آرزوی ثابت؛ اسم zi در ایستگاه زمان تحلیل می‌شود',
      analysedAt: ['core-time'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'آرزوی حسن ختام هنگام خداحافظی در طول روز. اسم ' },
        { ref: 'w-time-zi', display: 'zi' },
        { t: ' نکره است و صفت ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: ' پس از آن آمده است.' },
      ],
      en: [
        { t: 'Parting wish during daytime. Indefinite noun ' },
        { ref: 'w-time-zi', display: 'zi' },
        { t: ' followed by adjective ' },
        { ref: 'w-core-buna', display: 'bună' },
        { t: '.' },
      ],
    },
  },

  // --- تعارفات و ادب ---
  {
    id: 'p-core-va-rog',
    slug: 'core-va-rog',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-3-politeness',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Vă rog.',
      en: 'Please (formal).',
      fa: 'خواهش می‌کنم / لطفاً (رسمی).',
    },
    wordIds: ['w-core-va'],
    verbIds: ['v-core-a-ruga'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie ruga (DEX \'09)',
      url: 'https://dexonline.ro/definitie/ruga',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'فرمول ادب؛ پی‌بست vă در ایستگاه ضمایر تحلیل می‌شود',
      analysedAt: ['core-pronouns'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'فرمول ادب رسمی با ضمیر احترامی ' },
        { ref: 'w-core-va', display: 'vă' },
        { t: ' (در برابر ' },
        { ref: 'p-core-te-rog', display: 'te rog' },
        { t: ' خودمانی). ضمیر رسمی ' },
        { ref: 'w-core-dumneavoastra', display: 'dumneavoastră' },
        { t: ' با صیغه‌ی جمع ' },
        { ref: 'w-core-voi', display: 'voi' },
        { t: ' مطابقت می‌کند (' },
        { ref: 'p-core-va-rog', display: 'vă rog' },
        { t: ' = از شما خواهش می‌کنم).' },
      ],
      en: [
        { t: 'Formal politeness formula with clitic ' },
        { ref: 'w-core-va', display: 'vă' },
        { t: ' (contrasting with informal ' },
        { ref: 'p-core-te-rog', display: 'te rog' },
        { t: '). Formal ' },
        { ref: 'w-core-dumneavoastra', display: 'dumneavoastră' },
        { t: ' aligns with ' },
        { ref: 'w-core-voi', display: 'voi' },
        { t: ' plural verb/clitics.' },
      ],
    },
  },
  {
    id: 'p-core-te-rog',
    slug: 'te-rog',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-3-politeness',
    level: 'beginner',
    register: 'informal',
    intendedUse: 'comprehend',
    text: {
      ro: 'Te rog.',
      en: 'Please (informal).',
      fa: 'خواهش می‌کنم / لطفاً (خودمانی).',
    },
    wordIds: ['w-core-te'],
    verbIds: ['v-core-a-ruga'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie ruga (DEX \'09)',
      url: 'https://dexonline.ro/definitie/ruga',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'فرمول ادب خودمانی؛ پی‌بست te در ایستگاه ضمایر تحلیل می‌شود',
      analysedAt: ['core-pronouns'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'فرمول ادب خودمانی برای درخواست از دوستان و افراد صمیمی (در برابر ' },
        { ref: 'p-core-va-rog', display: 'vă rog' },
        { t: ' رسمی).' },
      ],
      en: [
        { t: 'Informal request formula among close friends (contrasting with formal ' },
        { ref: 'p-core-va-rog', display: 'vă rog' },
        { t: ').' },
      ],
    },
  },
  {
    id: 'p-core-va-multumesc',
    slug: 'va-multumesc',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-3-politeness',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Vă mulțumesc.',
      en: 'Thank you (formal).',
      fa: 'از شما متشکرم (رسمی).',
    },
    wordIds: ['w-core-va'],
    verbIds: ['v-core-a-multumi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma mulțumi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/mul%C8%9Bumi/paradigma',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'فرمول تشکر رسمی؛ پی‌بست vă در ایستگاه ضمایر تحلیل می‌شود',
      analysedAt: ['core-pronouns'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'تشکر رسمی با ضمیر برایی ' },
        { ref: 'w-core-va', display: 'vă' },
        { t: ' و اول شخص مفرد ' },
        { ref: 'w-multumesc', display: 'mulțumesc' },
        { t: '. برای احترام به شخص مخاطب (' },
        { ref: 'w-core-dumneavoastra', display: 'dumneavoastră' },
        { t: ') از ' },
        { ref: 'w-core-va', display: 'vă' },
        { t: ' استفاده می‌شود.' },
      ],
      en: [
        { t: 'Formal thank you combining clitic ' },
        { ref: 'w-core-va', display: 'vă' },
        { t: ' and first person singular ' },
        { ref: 'w-multumesc', display: 'mulțumesc' },
        { t: '.' },
      ],
    },
  },
  {
    id: 'p-core-multumim',
    slug: 'multumim',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-3-politeness',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Mulțumim.',
      en: 'We thank you / Thank you (collective).',
      fa: 'متشکریم / سپاسگزاریم.',
    },
    verbIds: ['v-core-a-multumi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma mulțumi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/mul%C8%9Bumi/paradigma',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'صیغه‌ی اول شخص جمع (ما) از فعل ' },
        { ref: 'v-core-a-multumi', display: 'a mulțumi' },
        { t: ' برای تشکر از طرف یک جمع یا خانواده.' },
      ],
      en: [
        { t: 'First person plural form of ' },
        { ref: 'v-core-a-multumi', display: 'a mulțumi' },
        { t: ' used when thanking on behalf of a group.' },
      ],
    },
  },
  {
    id: 'p-core-cu-placere',
    slug: 'core-cu-placere',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-3-politeness',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Cu plăcere.',
      en: "You're welcome / With pleasure.",
      fa: 'خواهش می‌کنم / با کمال میل.',
    },
    wordIds: ['w-core-placere'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — locutiune plăcere (DEX \'09)',
      url: 'https://dexonline.ro/definitie/pl%C4%83cere',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'پاسخ استاندارد و مؤدبانه به تشکر (' },
        { ref: 'w-multumesc', display: 'Mulțumesc' },
        { t: '). ترکیب حرف اضافه‌ی ' },
        { fn: 'cu' },
        { t: ' و اسم ' },
        { ref: 'w-core-placere', display: 'plăcere' },
        { t: '.' },
      ],
      en: [
        { t: 'Standard polite response to ' },
      ],
    },
  },
  {
    id: 'p-core-scuze',
    slug: 'scuze',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-4-apology',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Scuze.',
      en: 'Sorry / Excuses.',
      fa: 'ببخشید / پوزش.',
    },
    wordIds: ['w-core-scuza'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie scuză (DEX \'09)',
      url: 'https://dexonline.ro/definitie/scuz%C4%83',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'عذرخواهی کوتاه و روزمره با استفاده از صورت جمع اسم ' },
        { ref: 'w-core-scuza', display: 'scuză' },
        { t: '.' },
      ],
      en: [
        { t: 'Short everyday apology using the plural form of the noun ' },
        { ref: 'w-core-scuza', display: 'scuză' },
        { t: '.' },
      ],
    },
  },

  // --- گفتگوهای کوتاه و احوال‌پرسی ---
  {
    id: 'p-core-ce-mai-faceti',
    slug: 'ce-mai-faceti',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-5-how-are-you',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Ce mai faceți?',
      en: 'How are you? (formal/plural)',
      fa: 'حال شما چطور است؟ / چه خبر؟ (رسمی)',
    },
    wordIds: ['w-core-ce', 'w-core-mai-adv'],
    verbIds: ['v-core-a-face'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie face (DEX \'09)',
      url: 'https://dexonline.ro/definitie/face',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'فرمول احوال‌پرسی؛ واژه‌ی پرسشی ce در ایستگاه کلمات پرسشی تحلیل می‌شود',
      analysedAt: ['core-question-words'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'احوال‌پرسی رسمی یا خطاب به چند نفر با صیغه‌ی دوم‌شخص جمع ' },
        { ref: 'v-core-a-face', display: 'faceți' },
        { t: ' از فعل ' },
        { ref: 'v-core-a-face', display: 'a face' },
        { t: '. ضمیر احترامی ' },
        { ref: 'w-core-dumneavoastra', display: 'dumneavoastră' },
        { t: ' نیز همواره فعل جمع می‌گیرد. در برابر ' },
        { ref: 'p-core-ce-mai-faci', display: 'Ce mai faci' },
        { t: '? خودمانی.' },
      ],
      en: [
        { t: 'Formal greeting or addressed to multiple people using second-person plural ' },
        { ref: 'v-core-a-face', display: 'faceți' },
        { t: ' of ' },
        { ref: 'v-core-a-face', display: 'a face' },
        { t: '. Formal ' },
        { ref: 'w-core-dumneavoastra', display: 'dumneavoastră' },
        { t: ' always takes plural verb. Contrasts with informal ' },
        { ref: 'p-core-ce-mai-faci', display: 'Ce mai faci' },
        { t: '?.' },
      ],
    },
  },
  {
    id: 'p-core-ce-mai-faci',
    slug: 'ce-mai-faci',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-5-how-are-you',
    level: 'beginner',
    register: 'informal',
    intendedUse: 'comprehend',
    text: {
      ro: 'Ce mai faci?',
      en: 'How are you? (informal)',
      fa: 'حالت چطوره؟ / چه خبر؟ (خودمانی)',
    },
    wordIds: ['w-core-ce', 'w-core-mai-adv'],
    verbIds: ['v-core-a-face'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie face (DEX \'09)',
      url: 'https://dexonline.ro/definitie/face',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'همان، صورت خودمانی',
      analysedAt: ['core-question-words'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'احوال‌پرسی غیررسمی و صمیمانه با صیغه‌ی دوم‌شخص مفرد ' },
        { ref: 'v-core-a-face', display: 'faci' },
        { t: ' (در برابر ' },
        { ref: 'p-core-ce-mai-faceti', display: 'Ce mai faceți' },
        { t: '? رسمی). قید ' },
        { ref: 'w-core-mai-adv', display: 'mai' },
        { t: ' در اینجا نقش احوال‌پرسی دارد.' },
      ],
      en: [
        { t: 'Informal friendly greeting using second-person singular ' },
        { ref: 'v-core-a-face', display: 'faci' },
        { t: ' (contrasts with formal ' },
        { ref: 'p-core-ce-mai-faceti', display: 'Ce mai faceți' },
        { t: '?). Adverb ' },
        { ref: 'w-core-mai-adv', display: 'mai' },
        { t: ' functions as greeting marker.' },
      ],
    },
  },
  {
    id: 'p-core-bine-multumesc',
    slug: 'bine-multumesc',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-5-how-are-you',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Bine, mulțumesc.',
      en: 'Fine, thank you.',
      fa: 'خوبم، ممنون.',
    },
    wordIds: ['w-core-bine'],
    verbIds: ['v-core-a-multumi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — definitie bine / mulțumi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/bine',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'پاسخ متداول و مؤدبانه به احوال‌پرسی‌های ' },
        { ref: 'p-core-ce-mai-faci', display: 'Ce mai faci' },
        { t: '? و ' },
        { ref: 'p-core-ce-mai-faceti', display: 'Ce mai faceți' },
        { t: '?. ترکیب قید ' },
        { ref: 'w-core-bine', display: 'bine' },
        { t: ' و صیغه‌ی اول شخص ' },
        { ref: 'w-multumesc', display: 'mulțumesc' },
        { t: '.' },
      ],
      en: [
        { t: 'Standard polite response to greeting inquiries ' },
        { ref: 'p-core-ce-mai-faci', display: 'Ce mai faci' },
        { t: '? and ' },
        { ref: 'p-core-ce-mai-faceti', display: 'Ce mai faceți' },
        { t: '?. Combines adverb bine and verb ' },
        { ref: 'w-multumesc', display: 'mulțumesc' },
        { t: '.' },
      ],
    },
  },
  {
    id: 'p-core-cum-va-numiti',
    slug: 'cum-va-numiti',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-6-introduce',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Cum vă numiți?',
      en: 'What is your name? (formal)',
      fa: 'نام شما چیست؟ (رسمی)',
    },
    wordIds: ['w-core-cum', 'w-core-va'],
    verbIds: ['v-core-a-numi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma numi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/numi/paradigma',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'فرمول پرسیدن نام؛ cum در کلمات پرسشی و vă در ضمایر تحلیل می‌شوند',
      analysedAt: ['core-question-words', 'core-pronouns'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'پرسش رسمی درباره‌ی نام با ضمیر ' },
        { ref: 'w-core-va', display: 'vă' },
        { t: ' و صیغه‌ی دوم‌شخص جمع ' },
        { ref: 'v-core-a-numi', display: 'numiți' },
        { t: ' از فعل ' },
        { ref: 'v-core-a-numi', display: 'a numi' },
        { t: '. ضمیر احترامی ' },
        { ref: 'w-core-dumneavoastra', display: 'dumneavoastră' },
        { t: ' صیغه‌ی جمع می‌گیرد، حتی وقتی با یک نفر حرف می‌زنید.' },
      ],
      en: [
        { t: 'Formal inquiry about one' },
      ],
    },
  },
  {
    id: 'p-core-ma-numesc',
    slug: 'core-ma-numesc',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-6-introduce',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Mă numesc {{name}}.',
      en: 'My name is {{name}}.',
      fa: 'نام من {{name}} است.',
    },
    wordIds: ['w-core-ma'],
    verbIds: ['v-core-a-numi'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — paradigma numi (DEX \'09)',
      url: 'https://dexonline.ro/definitie/numi/paradigma',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'فرمول معرفی؛ پی‌بست mă در ایستگاه ضمایر تحلیل می‌شود',
      analysedAt: ['core-pronouns'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'فرمول استاندارد و مؤدبانه برای معرفی نام خود با ضمیر انعکاسی ' },
        { ref: 'w-core-ma', display: 'mă' },
        { t: ' و صیغه‌ی اول‌شخص مفرد ' },
        { ref: 'v-core-a-numi', display: 'numesc' },
        { t: ' از فعل ' },
        { ref: 'v-core-a-numi', display: 'a numi' },
        { t: '.' },
      ],
      en: [
        { t: 'Standard polite formula for self-introduction with reflexive ' },
        { ref: 'w-core-ma', display: 'mă' },
        { t: ' and first-person ' },
        { ref: 'v-core-a-numi', display: 'numesc' },
        { t: ' of ' },
        { ref: 'v-core-a-numi', display: 'a numi' },
        { t: '.' },
      ],
    },
  },
  {
    id: 'p-core-imi-pare-bine',
    slug: 'imi-pare-bine',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-6-introduce',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Îmi pare bine.',
      en: 'Pleased to meet you / Glad.',
      fa: 'خوش‌وقتم / خوشحالم.',
    },
    wordIds: ['w-core-imi', 'w-core-bine'],
    verbIds: ['v-core-a-parea'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie părea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/p%C4%83rea',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'فرمول آشنایی؛ پی‌بست îmi در ایستگاه ضمایر تحلیل می‌شود',
      analysedAt: ['core-pronouns'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'عبارت رایج هنگام آشنایی و معرفی به معنای «خوش‌وقتم». ساختار: ضمیر برایی ' },
        { ref: 'w-core-imi', display: 'îmi' },
        { t: ' + فعل سوم‌شخص ' },
        { ref: 'v-core-a-parea', display: 'pare' },
        { t: ' + قید ' },
        { ref: 'w-core-bine', display: 'bine' },
        { t: ' (ذیل مدخل ' },
        { ref: 'v-core-a-parea', display: 'părea' },
        { t: ' در فرهنگ لغت).' },
      ],
      en: [
        { t: 'Common expression upon meeting someone meaning ' },
      ],
    },
  },
  {
    id: 'p-core-imi-pare-rau',
    slug: 'core-imi-pare-rau',
    category: 'everyday',
    domain: 'core',
    stationId: 'core-greetings',
    stepId: 'greet-4-apology',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Îmi pare rău.',
      en: "I'm sorry.",
      fa: 'متأسفم.',
    },
    wordIds: ['w-core-imi', 'w-core-rau'],
    verbIds: ['v-core-a-parea'],
    source: {
      kind: 'common-usage',
      label: 'dexonline — expresie părea (DEX \'09)',
      url: 'https://dexonline.ro/definitie/p%C4%83rea',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    taughtAsFormula: {
      reason: 'فرمول تأسف؛ پی‌بست îmi در ایستگاه ضمایر تحلیل می‌شود',
      analysedAt: ['core-pronouns'],
    },
    status: 'published',
    isFree: true,
    usageNote: {
      fa: [
        { t: 'فرمول استاندارد برای ابراز تأسف و همدردی. ساختار: ضمیر برایی ' },
        { ref: 'w-core-imi', display: 'îmi' },
        { t: ' + فعل سوم‌شخص ' },
        { ref: 'v-core-a-parea', display: 'pare' },
        { t: ' + قید ' },
        { ref: 'w-core-rau', display: 'rău' },
        { t: ' (عیناً ذیل مدخل ' },
        { ref: 'v-core-a-parea', display: 'părea' },
        { t: ' در فرهنگ لغت نقل شده است).' },
      ],
      en: [
        { t: 'Standard formula for expressing regret or sympathy. Structure: dative clitic ' },
        { ref: 'w-core-imi', display: 'îmi' },
        { t: ' + 3rd person ' },
        { ref: 'v-core-a-parea', display: 'pare' },
        { t: ' + adverb ' },
        { ref: 'w-core-rau', display: 'rău' },
        { t: ' (cited directly under ' },
        { ref: 'v-core-a-parea', display: 'părea' },
        { t: ' in DEX).' },
      ],
    },
  },
];
