import { RomanianWord } from '@/lib/romanian/types';

/**
 * ماژول زمان و تقویم رومانیایی (dre-p164)
 * ایستگاه ۴ از حوزه‌ی هسته (core-time)
 *
 * شامل ۴۴ مدخل در ۴ گروه:
 * - گروه ۱ (۷ مدخل): روزهای هفته (همه با حروف کوچک، مفرد و جمع طبق منبع معتبر DOOM 3 / DOR)
 * - گروه ۲ (۱۲ مدخل): ماه‌ها (همه با حروف کوچک، substantiv masculin invar.)
 * - گروه ۳ (۷ مدخل): ساعت و اجزای بیان زمان
 * - گروه ۴ (۱۸ مدخل): زمان نسبی، دوره‌ها، بخش‌های روز و صفت‌های زمانی
 *
 * تمامی اقلام با status: 'draft'، reviewer: 'ai-only'، stationId: 'core-time'،
 * domains: ['core'] و منبع واقعی بدون فاصله یا %20 ثبت شده‌اند.
 */

export const CORE_TIME: RomanianWord[] = [
  // ==========================================================================
  // گروه ۱: روزهای هفته (۷ مدخل)
  // ==========================================================================
  {
    id: 'w-time-luni',
    lemma: 'luni',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'lunea',
    plural: 'luni',
    translations: {
      en: 'Monday',
      fa: 'دوشنبه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DOOM 3 / DOR)',
      url: 'https://dexonline.ro/definitie/luni',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'نام روزهای هفته در زبان رومانیایی با حروف کوچک نوشته می‌شود (luni، نه Luni). واژه‌ی «luni» هم به معنای «دوشنبه» است و هم صورت جمع «lună» (ماه‌ها). صورت معرفه‌ی آن «lunea» است و برای بیان عادت یا برنامه‌ی کاری هفتگی به کار می‌رود («دوشنبه‌ها»).',
      en: 'Days of the week in Romanian are written in lowercase (luni, not Luni). The word "luni" denotes "Monday" and also serves as the plural of "lună" (months). Its definite form "lunea" is used for regular weekly habits or recurring schedules ("on Mondays").',
    },
  },
  {
    id: 'w-time-marti',
    lemma: 'marți',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'marțea',
    plural: 'marți',
    translations: {
      en: 'Tuesday',
      fa: 'سه‌شنبه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DOOM 3 / DOR)',
      url: 'https://dexonline.ro/definitie/mar%C8%9Bi',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود. صورت معرفه‌ی آن «marțea» به معنای «سه‌شنبه‌ها» (به طور مرتب) است. توجه کنید که این واژه با «martie» (ماه مارس) که یک حرف بیشتر دارد اشتباه نشود.',
      en: 'Written in lowercase. The definite form "marțea" means "on Tuesdays" (habitually). Be careful not to confuse it with "martie" (the month of March).',
    },
  },
  {
    id: 'w-time-miercuri',
    lemma: 'miercuri',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'miercurea',
    plural: 'miercuri',
    translations: {
      en: 'Wednesday',
      fa: 'چهارشنبه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DOOM 3 / DOR)',
      url: 'https://dexonline.ro/definitie/miercuri',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود. صورت معرفه‌ی آن «miercurea» بیانگر استمرار هفتگی («چهارشنبه‌ها») است.',
      en: 'Written in lowercase. The definite form "miercurea" denotes recurring weekly occurrences ("on Wednesdays").',
    },
  },
  {
    id: 'w-time-joi',
    lemma: 'joi',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'joia',
    plural: 'joi',
    translations: {
      en: 'Thursday',
      fa: 'پنج‌شنبه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DOOM 3 / DOR)',
      url: 'https://dexonline.ro/definitie/joi',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود. صورت معرفه‌ی آن «joia» به معنای «پنج‌شنبه‌ها» است.',
      en: 'Written in lowercase. The definite form "joia" means "on Thursdays".',
    },
  },
  {
    id: 'w-time-vineri',
    lemma: 'vineri',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'vinerea',
    plural: 'vineri',
    translations: {
      en: 'Friday',
      fa: 'جمعه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DOOM 3 / DOR)',
      url: 'https://dexonline.ro/definitie/vineri',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود. صورت معرفه‌ی آن «vinerea» به معنای «جمعه‌ها» به کار می‌رود.',
      en: 'Written in lowercase. The definite form "vinerea" means "on Fridays".',
    },
  },
  {
    id: 'w-time-sambata',
    lemma: 'sâmbătă',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'sâmbăta',
    plural: 'sâmbete',
    translations: {
      en: 'Saturday',
      fa: 'شنبه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DOOM 3 / DOR)',
      url: 'https://dexonline.ro/definitie/s%C3%A2mb%C4%83t%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'بر خلاف پنج روز نخست هفته که صورت جمع هم‌شکل با مفرد دارند، واژه‌ی «sâmbătă» دارای صورت جمع متمایز «sâmbete» است. صورت معرفه‌ی مفرد آن «sâmbăta» به معنای «شنبه‌ها» است.',
      en: 'Unlike the first five days of the week which have identical plural forms, "sâmbătă" has the distinct plural "sâmbete". Its singular definite form "sâmbăta" means "on Saturdays".',
    },
  },
  {
    id: 'w-time-duminica',
    lemma: 'duminică',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'duminica',
    plural: 'duminici',
    translations: {
      en: 'Sunday',
      fa: 'یکشنبه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DOOM 3 / DOR)',
      url: 'https://dexonline.ro/definitie/duminic%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'دارای صورت جمع متمایز «duminici» است. صورت معرفه‌ی آن «duminica» به معنای «یکشنبه‌ها» استفاده می‌شود.',
      en: 'Features the distinct plural form "duminici". Its definite form "duminica" means "on Sundays".',
    },
  },

  // ==========================================================================
  // گروه ۲: ماه‌ها (۱۲ مدخل)
  // ==========================================================================
  {
    id: 'w-time-ianuarie',
    lemma: 'ianuarie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'January',
      fa: 'ژانویه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/ianuarie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'نام ماه‌ها در رومانیایی با حرف کوچک نوشته می‌شود. اسم مذکر بدون صرف است.',
      en: 'Month names in Romanian are written in lowercase. It is an invariable masculine noun.',
    },
  },
  {
    id: 'w-time-februarie',
    lemma: 'februarie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'February',
      fa: 'فوریه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/februarie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود.',
      en: 'Written in lowercase.',
    },
  },
  {
    id: 'w-time-martie',
    lemma: 'martie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'March',
      fa: 'مارس',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/martie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قاعده‌ی تاریخ: برای روز اول ماه از عدد ترتیبی استفاده می‌شود («întâi martie»)، اما برای روزهای دیگر از عدد اصلی استفاده می‌شود («doi martie»، نه «al doilea»). توجه: با «marți» (سه‌شنبه) اشتباه نشود.',
      en: 'Date rule: The first day of the month uses an ordinal numeral ("întâi martie"), while subsequent days use cardinal numerals ("doi martie", not "al doilea"). Warning: Do not confuse with "marți" (Tuesday).',
    },
  },
  {
    id: 'w-time-aprilie',
    lemma: 'aprilie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'April',
      fa: 'آوریل',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/aprilie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود.',
      en: 'Written in lowercase.',
    },
  },
  {
    id: 'w-time-mai',
    lemma: 'mai',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'May',
      fa: 'مه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/mai',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'واژه‌ی «mai» دارای سه کاربرد کاملاً متمایز است: ۱) اسم ماه پنجم سال (ماه مه)، ۲) قید تفضیلی به معنای «بیشتر/دیگر» («mai mult»)، ۳) جزء صرفی.',
      en: 'The word "mai" has three distinct roles: 1) the fifth month of the year (May), 2) comparative adverb meaning "more" / "else" ("mai mult"), 3) grammatical aspect/tense marker.',
    },
  },
  {
    id: 'w-time-iunie',
    lemma: 'iunie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'June',
      fa: 'ژوئن',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/iunie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود.',
      en: 'Written in lowercase.',
    },
  },
  {
    id: 'w-time-iulie',
    lemma: 'iulie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'July',
      fa: 'ژوئیه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/iulie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود.',
      en: 'Written in lowercase.',
    },
  },
  {
    id: 'w-time-august',
    lemma: 'august',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'August',
      fa: 'اوت',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/august',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'این مدخل نشان‌دهنده‌ی ماه هشتم سال (اوت) است. همنگاشت آن صفت «august» به معنای «باشکوه/والامقام» و لقب امپراتوران روم است.',
      en: 'This entry represents the eighth month of the year (August). Its homograph is the adjective "august" meaning "majestic/venerable" or imperial title.',
    },
  },
  {
    id: 'w-time-septembrie',
    lemma: 'septembrie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'September',
      fa: 'سپتامبر',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/septembrie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود.',
      en: 'Written in lowercase.',
    },
  },
  {
    id: 'w-time-octombrie',
    lemma: 'octombrie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'October',
      fa: 'اکتبر',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/octombrie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود.',
      en: 'Written in lowercase.',
    },
  },
  {
    id: 'w-time-noiembrie',
    lemma: 'noiembrie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'November',
      fa: 'نوامبر',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/noiembrie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود.',
      en: 'Written in lowercase.',
    },
  },
  {
    id: 'w-time-decembrie',
    lemma: 'decembrie',
    pos: 'noun',
    gender: 'm',
    translations: {
      en: 'December',
      fa: 'دسامبر',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'comprehend',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/decembrie',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'با حرف کوچک نوشته می‌شود.',
      en: 'Written in lowercase.',
    },
  },

  // ==========================================================================
  // گروه ۳: ساعت و اجزای بیان زمان (۷ مدخل)
  // ==========================================================================
  {
    id: 'w-time-ora',
    lemma: 'oră',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'ora',
    plural: 'ore',
    translations: {
      en: 'hour / time (clock)',
      fa: 'ساعت (واحد زمان)',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/or%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قاعده‌ی بیان زمان و ساعت: ۱) برای ساعت ۱، صورت پایه استفاده می‌شود: «ora unu» (نه «una»؛ زیرا به عنوان شماره و برچسب به کار می‌رود). ۲) برای ساعت‌های ۲ و ۱۲ از صورت مؤنث عدد استفاده می‌شود: «ora două» و «ora douăsprezece». ۳) برای گذشت زمان از «și» («două și zece»، «două și jumătate»، «două și un sfert») و برای مانده تا ساعت بعدی از «fără» («două fără zece»، «două fără un sfert») استفاده می‌شود. ۴) جمله‌ی رایج پرسیدن ساعت: «La ce oră?» (در چه ساعتی؟) و پاسخ: «La ora două.» (در ساعت ۲).',
      en: 'Telling time rules: 1) Hour 1 uses the base cardinal: "ora unu" (not "una", as it acts as an identifying numeral label). 2) Hours 2 and 12 use the feminine form: "ora două" and "ora douăsprezece". 3) Use "și" for minutes past ("două și zece", "două și jumătate", "două și un sfert") and "fără" for minutes to ("două fără zece", "două fără un sfert"). 4) Essential question: "La ce oră?" (At what time?) and answer: "La ora două." (At two o\'clock).',
    },
  },
  {
    id: 'w-time-minut',
    lemma: 'minut',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'minutul',
    plural: 'minute',
    translations: {
      en: 'minute',
      fa: 'دقیقه',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/minut',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'اسم خنثی؛ جمع آن «minute» است.',
      en: 'Neuter noun; its plural is "minute".',
    },
  },
  {
    id: 'w-time-ceas',
    lemma: 'ceas',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'ceasul',
    plural: 'ceasuri',
    translations: {
      en: 'clock / watch',
      fa: 'ساعت (دستگاه)',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/ceas',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'برای دستگاه ساعت فیزیکی (مچی یا دیواری) به کار می‌رود؛ بر خلاف «oră» که واحد سنجش زمان است.',
      en: 'Refers to the physical clock or watch device, in contrast to "oră" which denotes the hour of time.',
    },
  },
  {
    id: 'w-time-jumatate',
    lemma: 'jumătate',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'jumătatea',
    plural: 'jumătăți',
    translations: {
      en: 'half',
      fa: 'نیم',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/jum%C4%83tate',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'در بیان ساعت همراه با «și» می‌آید: «două și jumătate» (ساعت دو و نیم).',
      en: 'Used with "și" when telling time: "două și jumătate" (half past two).',
    },
  },
  {
    id: 'w-time-sfert',
    lemma: 'sfert',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'sfertul',
    plural: 'sferturi',
    translations: {
      en: 'quarter',
      fa: 'ربع',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/sfert',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'در بیان ساعت با حرف تعریف نامعین می‌آید: «două și un sfert» (دو و ربع) و «două fără un sfert» (یک ربع مانده به دو).',
      en: 'Used with the indefinite article in clock times: "două și un sfert" (quarter past two) and "două fără un sfert" (quarter to two).',
    },
  },
  {
    id: 'w-time-fara',
    lemma: 'fără',
    pos: 'prep',
    translations: {
      en: 'minus / without',
      fa: 'بدون / مانده به (در ساعت)',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/f%C4%83r%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'حرف اضافه برای بیان مانده به ساعت بعدی: «două fără zece» (ده دقیقه به دو) و «două fără un sfert» (یک ربع به دو).',
      en: 'Preposition indicating minutes to the next hour: "două fără zece" (ten to two) and "două fără un sfert" (quarter to two).',
    },
  },
  {
    id: 'w-time-fix',
    lemma: 'fix',
    pos: 'adv',
    translations: {
      en: 'sharp / on the dot',
      fa: 'دقیقاً / سرِ ساعت',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/fix',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'به عنوان قید برای نشان دادن ساعت دقیق به کار می‌رود: «ora două fix» (ساعت دو دقیقاً).',
      en: 'Used adverbially to designate exact time: "ora două fix" (two o\'clock sharp).',
    },
  },

  // ==========================================================================
  // گروه ۴: زمان نسبی، دوره‌ها، بخش‌های روز و صفت‌ها (۱۸ مدخل)
  // ==========================================================================
  // --- قیدها (۸ مدخل) ---
  {
    id: 'w-time-azi',
    lemma: 'azi',
    pos: 'adv',
    translations: {
      en: 'today',
      fa: 'امروز',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/azi',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید زمان به معنای امروز؛ هم‌معنی کوتاه‌تر «astăzi».',
      en: 'Adverb of time meaning today; shorter equivalent of "astăzi".',
    },
  },
  {
    id: 'w-time-astazi',
    lemma: 'astăzi',
    pos: 'adv',
    translations: {
      en: 'today',
      fa: 'امروز',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/ast%C4%83zi',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید زمان به معنای امروز؛ مترادف «azi».',
      en: 'Adverb of time meaning today; synonym of "azi".',
    },
  },
  {
    id: 'w-time-maine',
    lemma: 'mâine',
    pos: 'adv',
    translations: {
      en: 'tomorrow',
      fa: 'فردا',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/m%C3%A2ine',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید زمان به معنای روز بعد.',
      en: 'Adverb of time meaning tomorrow.',
    },
  },
  {
    id: 'w-time-poimaine',
    lemma: 'poimâine',
    pos: 'adv',
    translations: {
      en: 'the day after tomorrow',
      fa: 'پس‌فردا',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/poim%C3%A2ine',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید زمان به معنای روز بعد از فردا.',
      en: 'Adverb of time meaning the day after tomorrow.',
    },
  },
  {
    id: 'w-time-ieri',
    lemma: 'ieri',
    pos: 'adv',
    translations: {
      en: 'yesterday',
      fa: 'دیروز',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/ieri',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید زمان به معنای روز گذشته.',
      en: 'Adverb of time meaning yesterday.',
    },
  },
  {
    id: 'w-time-acum',
    lemma: 'acum',
    pos: 'adv',
    translations: {
      en: 'now',
      fa: 'اکنون / حالا',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/acum',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید زمان برای زمان حال و زمان حاضر.',
      en: 'Adverb of time indicating the present moment.',
    },
  },
  {
    id: 'w-time-devreme',
    lemma: 'devreme',
    pos: 'adv',
    translations: {
      en: 'early',
      fa: 'زود',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/devreme',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید به معنای در وقت اولیه یا پیش از موعد مقرر.',
      en: 'Adverb meaning early or ahead of schedule.',
    },
  },
  {
    id: 'w-time-tarziu',
    lemma: 'târziu',
    pos: 'adv',
    translations: {
      en: 'late',
      fa: 'دیر',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/t%C3%A2rziu',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید به معنای پس از موعد یا دیر وقت.',
      en: 'Adverb meaning late or after the expected time.',
    },
  },

  // --- اسم‌های دوره (۴ مدخل) ---
  {
    id: 'w-time-zi',
    lemma: 'zi',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'ziua',
    plural: 'zile',
    translations: {
      en: 'day',
      fa: 'روز',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/zi',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'اسم مؤنث؛ صورت معرفه‌ی آن «ziua» و جمع آن «zile» است.',
      en: 'Feminine noun; definite form is "ziua" and plural is "zile".',
    },
  },
  {
    id: 'w-time-saptamana',
    lemma: 'săptămână',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'săptămâna',
    plural: 'săptămâni',
    translations: {
      en: 'week',
      fa: 'هفته',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/s%C4%83pt%C4%83m%C3%A2n%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'اسم مؤنث؛ صورت معرفه «săptămâna» و جمع آن «săptămâni» است.',
      en: 'Feminine noun; definite form is "săptămâna" and plural is "săptămâni".',
    },
  },
  {
    id: 'w-time-luna',
    lemma: 'lună',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'luna',
    plural: 'luni',
    translations: {
      en: 'month / moon',
      fa: 'ماه (تقویمی و آسمان)',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/lun%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'واژه‌ی «lună» همنگاشت است و دارای دو معنای بنیادین است: ۱) ماه تقویمی (دوازدهمین بخش از سال)، ۲) کره‌ی ماه در آسمان. صورت جمع آن «luni» با نام روز دوشنبه هم‌شکل است.',
      en: 'The word "lună" is polysemous with two core meanings: 1) calendar month, 2) the celestial moon. Its plural form "luni" is homographic with the day name "luni" (Monday).',
    },
  },
  {
    id: 'w-time-an',
    lemma: 'an',
    pos: 'noun',
    gender: 'm',
    definiteForm: 'anul',
    plural: 'ani',
    translations: {
      en: 'year',
      fa: 'سال',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/an',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'اسم مذکر؛ صورت معرفه «anul» و جمع آن «ani» است.',
      en: 'Masculine noun; definite form is "anul" and plural is "ani".',
    },
  },

  // --- بخش‌های روز (۴ مدخل) ---
  {
    id: 'w-time-dimineata',
    lemma: 'dimineață',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'dimineața',
    plural: 'dimineți',
    translations: {
      en: 'morning',
      fa: 'صبح',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/diminea%C8%9B%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'صورت معرفه‌ی آن «dimineața» علاوه بر «صبح»، به صورت قیدی به معنای «صبح‌ها / هر روز صبح» به کار می‌رود.',
      en: 'The definite form "dimineața" can function adverbially meaning "in the morning" or "mornings (regularly)".',
    },
  },
  {
    id: 'w-time-dupa-amiaza',
    lemma: 'după-amiază',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'după-amiaza',
    plural: 'după-amiezi',
    translations: {
      en: 'afternoon',
      fa: 'بعدازظهر',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/dup%C4%83-amiaz%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'واژه‌ی مرکب استاندارد با خط‌تیره‌ی میانی. صورت معرفه‌ی آن «după-amiaza» است.',
      en: 'Standard compound noun with an internal hyphen. Its definite form is "după-amiaza".',
    },
  },
  {
    id: 'w-time-seara',
    lemma: 'seară',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'seara',
    plural: 'seri',
    translations: {
      en: 'evening',
      fa: 'عصر / غروب',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/sear%C4%83',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'صورت معرفه‌ی آن «seara» به صورت قیدی به معنای «شب‌ها / عصرها (به‌طور مرتب)» نیز به کار می‌رود.',
      en: 'The definite form "seara" is also used adverbially to mean "in the evening" or "evenings (habitually)".',
    },
  },
  {
    id: 'w-time-noapte',
    lemma: 'noapte',
    pos: 'noun',
    gender: 'f',
    definiteForm: 'noaptea',
    plural: 'nopți',
    translations: {
      en: 'night',
      fa: 'شب',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/noapte',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'صورت معرفه‌ی آن «noaptea» به صورت قیدی به معنای «شب‌ها / در طول شب» کاربرد دارد.',
      en: 'The definite form "noaptea" is also used adverbially meaning "at night" or "nights".',
    },
  },

  // --- صفت‌ها (۲ مدخل) ---
  {
    id: 'w-time-viitor',
    lemma: 'viitor',
    pos: 'adj',
    translations: {
      en: 'next / future',
      fa: 'آینده / بعدی',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/viitor',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'صفت برای اشاره به دوره‌ی بعدی؛ مانند هفته‌ی بعد یا سال بعد.',
      en: 'Adjective used to refer to subsequent time periods, e.g. next week or next year.',
    },
  },
  {
    id: 'w-time-trecut',
    lemma: 'trecut',
    pos: 'adj',
    translations: {
      en: 'past / last',
      fa: 'گذشته / قبلی',
    },
    domains: ['core'],
    stationId: 'core-time',
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: 'dexonline (DEX / DOOM)',
      url: 'https://dexonline.ro/definitie/trecut',
      retrievedAt: '2026-09-24',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'صفت برای اشاره به دوره‌ی زمانی سپری‌شده؛ مانند هفته‌ی گذشته.',
      en: 'Adjective used to refer to past time periods, e.g. last week.',
    },
  },
];
