export const NUMBER_GENDER_FOUNDATION_LESSON = {
  titleFa: 'یک و دو: عدد با جنس اسم هماهنگ می‌شود',
  titleEn: 'One and two: match the number to the noun',
  introFa: 'برای گفتن «یک»، اسم مذکر و خنثی با un و اسم مؤنث با o می‌آید. برای «دو»، مذکر doi و مؤنث/خنثی două می‌گیرد. اسم خنثی در مفرد مانند مذکر و در جمع مانند مؤنث رفتار می‌کند.',
  introEn: 'For “one”, masculine and neuter nouns take un; feminine nouns take o. For “two”, masculine takes doi and feminine/neuter take două. A neuter noun behaves like masculine in the singular and feminine in the plural.',
  samples: [
    {
      wordId: 'w-elev', gender: 'm',
      singular: 'un elev', pluralForm: 'doi elevi',
      singularFa: 'یک دانش‌آموز', pluralFa: 'دو دانش‌آموز',
      singularEn: 'one pupil', pluralEn: 'two pupils',
      singularPronFa: 'اُن یِلِو', pluralPronFa: 'دُوی یِلِوی',
      singularIPA: '/un eˈlev/', pluralIPA: '/doj eˈlevʲ/',
      noteFa: 'elev اسم مذکر است: un در مفرد و doi در جمع. صورت جمع elevi است.',
      noteEn: 'Elev is masculine: un in the singular and doi in the plural. Its plural is elevi.',
    },
    {
      wordId: 'w-casa', gender: 'f',
      singular: 'o casă', pluralForm: 'două case',
      singularFa: 'یک خانه', pluralFa: 'دو خانه',
      singularEn: 'one house', pluralEn: 'two houses',
      singularPronFa: 'او کاسَ', pluralPronFa: 'دُوَ کاسِ',
      singularIPA: '/o ˈka.sə/', pluralIPA: '/do̯ə ˈka.se/',
      noteFa: 'casă اسم مؤنث است: o در مفرد و două در جمع. صورت جمع case است.',
      noteEn: 'Casă is feminine: o in the singular and două in the plural. Its plural is case.',
    },
    {
      wordId: 'w-bilet', gender: 'n',
      singular: 'un bilet', pluralForm: 'două bilete',
      singularFa: 'یک بلیت', pluralFa: 'دو بلیت',
      singularEn: 'one ticket', pluralEn: 'two tickets',
      singularPronFa: 'اُون بی‌لِت', pluralPronFa: 'دُوَ بی‌لِتِ',
      singularIPA: '/un biˈlet/', pluralIPA: '/do̯ə biˈle.te/',
      noteFa: 'bilet اسم خنثی است: در مفرد un می‌گیرد، اما در جمع با două می‌آید؛ صورت جمع bilete است.',
      noteEn: 'Bilet is neuter: it takes un in the singular, but două in the plural; its plural is bilete.',
    },
  ],
  prompts: [
    { sample: 0, number: 'singular', fa: 'یک دانش‌آموز', en: 'one pupil' },
    { sample: 0, number: 'plural', fa: 'دو دانش‌آموز', en: 'two pupils' },
    { sample: 1, number: 'singular', fa: 'یک خانه', en: 'one house' },
    { sample: 1, number: 'plural', fa: 'دو خانه', en: 'two houses' },
    { sample: 2, number: 'singular', fa: 'یک بلیت', en: 'one ticket' },
    { sample: 2, number: 'plural', fa: 'دو بلیت', en: 'two tickets' },
  ],
  speakingQuestion: 'Un bilet sau două bilete?',
  speakingPhrase: 'Două bilete, vă rog.',
  speakingFa: 'دو بلیت، لطفاً.',
  speakingEn: 'Two tickets, please.',
  speakingNoteFa: 'درخواست را با الگوی neuter در جمع می‌سازید: două bilete.',
  speakingNoteEn: 'The request uses the neuter plural pattern: două bilete.',
} as const;
