import { RomanianPhrase } from '@/lib/romanian/types';

export const PILOT_PHRASES: RomanianPhrase[] = [
  {
    id: 'everyday-001',
    slug: 'buna-ziua',
    category: 'everyday',
    domain: 'core',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Bună ziua!',
      en: 'Good afternoon / Hello!',
      fa: 'سلام / روز بخیر!',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-002',
    slug: 'ma-numesc',
    category: 'everyday',
    domain: 'core',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Mă numesc {{name}}.',
      en: 'My name is {{name}}.',
      fa: 'اسم من {{name}} است.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-003',
    slug: 'nu-am-inteles',
    category: 'everyday',
    domain: 'core',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Nu am înțeles. Puteți repeta, vă rog?',
      en: "I didn't understand. Could you repeat, please?",
      fa: 'متوجه نشدم. لطفاً می‌توانید تکرار کنید؟',
    },
    informalVariant: {
      ro: 'Nu am înțeles. Poți repeta, te rog?',
      note: 'صورت غیررسمی — فقط برای درک. این جمله را به کاربر پیشنهاد نکن.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'transport-001',
    slug: 'unde-este-statia-de-metrou',
    category: 'transport',
    domain: 'core',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Unde este stația de metrou?',
      en: 'Where is the metro station?',
      fa: 'ایستگاه مترو کجاست؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'transport-002',
    slug: 'un-bilet-va-rog',
    category: 'transport',
    domain: 'core',
    level: 'beginner',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Un bilet, vă rog.',
      en: 'One ticket, please.',
      fa: 'یک بلیت لطفاً.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'shopping-001',
    slug: 'cat-costa',
    category: 'shopping',
    domain: 'core',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Cât costă?',
      en: 'How much does it cost?',
      fa: 'قیمتش چقدر است؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'shopping-002',
    slug: 'pot-plati-cu-cardul',
    category: 'shopping',
    domain: 'core',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Pot plăti cu cardul?',
      en: 'Can I pay by card?',
      fa: 'می‌توانم با کارت پرداخت کنم؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'banking-001',
    slug: 'deschid-un-cont-bancar',
    category: 'banking',
    domain: 'banking',
    level: 'elementary',
    register: 'formal',
    intendedUse: 'produce',
    text: {
      ro: 'Aș dori să deschid un cont bancar.',
      en: 'I would like to open a bank account.',
      fa: 'می‌خواهم یک حساب بانکی باز کنم.',
    },
    vocabulary: [
      { ro: 'cont bancar', en: 'bank account', fa: 'حساب بانکی' },
      { ro: 'a deschide', en: 'to open', fa: 'باز کردن' },
    ],
    journeys: ['relocation', 'study', 'work', 'business'],
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'healthcare-001',
    slug: 'am-o-programare',
    category: 'healthcare',
    domain: 'healthcare',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Am o programare.',
      en: 'I have an appointment.',
      fa: 'من وقت قبلی دارم.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'review',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'administration-001',
    slug: 'unde-depun-documentele',
    category: 'administration',
    domain: 'administration',
    level: 'elementary',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Unde trebuie să depun documentele?',
      en: 'Where do I need to submit the documents?',
      fa: 'مدارک را کجا باید تحویل بدهم؟',
    },
    journeys: ['relocation', 'work', 'study'],
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'review',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'school-001',
    slug: 'fiul-meu-este-elev-aici',
    category: 'school',
    domain: 'school',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Fiul meu este elev aici.',
      en: 'My son is a student here.',
      fa: 'پسرم اینجا دانش‌آموز است.',
    },
    journeys: ['family'],
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'emergency-001',
    slug: 'am-nevoie-de-ajutor',
    category: 'emergency',
    domain: 'core',
    level: 'beginner',
    register: 'neutral',
    intendedUse: 'produce',
    text: {
      ro: 'Am nevoie de ajutor.',
      en: 'I need help.',
      fa: 'به کمک نیاز دارم.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA product spec v2 — pilot set',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
];
