import {
  DomainMeta,
  RomanianWord,
  RomanianVerb,
  RomanianGrapheme,
  RomanianDialogue,
} from '@/lib/romanian/types';

export const SEED_DOMAINS: DomainMeta[] = [
  {
    id: 'core',
    titleFa: 'هسته',
    titleEn: 'Core',
    order: 0,
    estimatedWeeks: 2,
    stationOrder: 'sequential',
    stations: [
      { id: 'core-pronouns', slug: 'pronume', titleFa: 'ضمایر', titleRo: 'Pronume', order: 1 },
      { id: 'core-question-words', slug: 'cuvinte-interogative', titleFa: 'کلمات پرسشی', titleRo: 'Cuvinte interogative', order: 2 },
      { id: 'core-numbers', slug: 'numere', titleFa: 'اعداد', titleRo: 'Numere', order: 3 },
      { id: 'core-time', slug: 'timp', titleFa: 'زمان', titleRo: 'Timp', order: 4 },
      { id: 'core-greetings', slug: 'salutari', titleFa: 'احوال‌پرسی و ادب', titleRo: 'Salutări și politețe', order: 5 },
    ],
    sourcingPolicy: 'common-usage-ok',
    categories: ['everyday', 'transport', 'shopping', 'healthcare', 'emergency'],
    maxItems: 250,
  },
  {
    id: 'banking',
    titleFa: 'بانک',
    titleEn: 'Banking',
    order: 4,
    estimatedWeeks: 1,
    stationOrder: 'sequential',
    stations: [],
    sourcingPolicy: 'common-usage-ok',
    categories: ['banking'],
  },
  {
    id: 'healthcare',
    titleFa: 'پزشک و درمان',
    titleEn: 'Healthcare',
    order: 6,
    estimatedWeeks: 2,
    stationOrder: 'sequential',
    stations: [],
    sourcingPolicy: 'must-be-sourced',
    categories: ['healthcare'],
  },
  {
    id: 'administration',
    titleFa: 'امور اداری',
    titleEn: 'Administration',
    order: 7,
    estimatedWeeks: 2,
    stationOrder: 'sequential',
    stations: [],
    sourcingPolicy: 'must-be-sourced',
    categories: ['administration'],
  },
  {
    id: 'school',
    titleFa: 'مدرسه',
    titleEn: 'School',
    order: 8,
    estimatedWeeks: 1,
    stationOrder: 'grouped',
    stations: [],
    sourcingPolicy: 'common-usage-ok',
    categories: ['school'],
  },
];

export const SEED_WORDS: RomanianWord[] = [
  {
    id: 'w-cont',
    lemma: 'cont',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'contul',
    plural: 'conturi',
    translations: { en: 'account', fa: 'حساب' },
    domains: ['core'],
    intendedUse: 'produce',
    source: { kind: 'common-usage', label: 'DORVIA seed' },
    reviewer: 'ai-only',
    status: 'published',
  },
  {
    id: 'w-pasaport',
    lemma: 'pașaport',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'pașaportul',
    plural: 'pașapoarte',
    translations: { en: 'passport', fa: 'گذرنامه' },
    domains: ['core'],
    intendedUse: 'produce',
    source: { kind: 'common-usage', label: 'DORVIA seed' },
    reviewer: 'ai-only',
    status: 'published',
  },
  {
    id: 'w-incet',
    lemma: 'încet',
    pos: 'adv',
    translations: { en: 'slowly / quietly', fa: 'آهسته / آرام' },
    domains: ['core'],
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: "dexonline (DEX '09 / DOOM 3)",
      url: 'https://dexonline.ro/definitie/%C3%AEncet',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: 'قید به معنای «آرام، آهسته، بی‌صدا». در عبارت‌هایی چون «mai încet» به کار می‌رود.',
      en: 'Adverb meaning "slowly / quietly / softly". Used in expressions like "mai încet".',
    },
  },
];

export const SEED_VERBS: RomanianVerb[] = [
  {
    id: 'v-a-fi',
    infinitive: 'a fi',
    translations: { en: 'to be', fa: 'بودن' },
    domains: ['core'],
    conjugation: {
      prezent: {
        eu: 'sunt',
        tu: 'ești',
        el: 'este',
        noi: 'suntem',
        voi: 'sunteți',
        ei: 'sunt',
      },
      conjunctiv: {
        eu: 'fiu',
        tu: 'fii',
        el: 'fie',
        noi: 'fim',
        voi: 'fiți',
        ei: 'fie',
      },
    },
    participiu: 'fost',
    source: {
      label: 'dexonline — paradigma (DOOM 3)',
      url: 'https://dexonline.ro/definitie/fi/paradigma',
      retrievedAt: '2026-09-22',
    },
    reviewer: 'ai-only',
    status: 'published',
  },
  {
    id: 'v-a-avea',
    infinitive: 'a avea',
    translations: { en: 'to have', fa: 'داشتن' },
    domains: ['core'],
    conjugation: {
      prezent: {
        eu: 'am',
        tu: 'ai',
        el: 'are',
        noi: 'avem',
        voi: 'aveți',
        ei: 'au',
      },
      conjunctiv: {
        eu: 'am',
        tu: 'ai',
        el: 'aibă',
        noi: 'avem',
        voi: 'aveți',
        ei: 'aibă',
      },
    },
    participiu: 'avut',
    source: {
      label: "dexonline — paradigma (DEX '09)",
      url: 'https://dexonline.ro/definitie/avea/paradigma',
      retrievedAt: '2026-09-22',
    },
    reviewer: 'ai-only',
    status: 'published',
  },
];

export const SEED_GRAPHEMES: RomanianGrapheme[] = [];

export const SEED_DIALOGUES: RomanianDialogue[] = [];
