import {
  DomainMeta,
  RomanianWord,
  RomanianVerb,
  RomanianGrapheme,
  RomanianDialogue,
} from '@/lib/romanian/types';

export const SEED_DOMAINS: DomainMeta[] = [
  {
    id: 'core',
    titleFa: 'هسته',
    titleEn: 'Core',
    order: 0,
    estimatedWeeks: 2,
    stationOrder: 'sequential',
    stations: [
      {
        id: 'core-greetings',
        slug: 'salutari',
        titleFa: 'احوال‌پرسی و ادب',
        titleRo: 'Salutări și politețe',
        order: 1,
        isFree: true,
        steps: [
          {
            id: 'greet-1-hello',
            order: 1,
            titleFa: 'سلام گفتن',
            titleRo: 'Salutul',
            canFa: 'می‌تواند در هر ساعت روز سلام کند',
            canEn: 'Can greet someone at any time of day',
          },
          {
            id: 'greet-2-yes-no-bye',
            order: 2,
            titleFa: 'بله، نه، خداحافظ',
            titleRo: 'Da, nu, la revedere',
            canFa: 'می‌تواند گفت‌وگو را باز و بسته کند',
            canEn: 'Can open and close an exchange',
          },
          {
            id: 'greet-3-politeness',
            order: 3,
            titleFa: 'ادب',
            titleRo: 'Politețe',
            canFa: 'می‌تواند خواهش و تشکر کند، و رسمی را از خودمانی جدا کند',
            canEn: 'Can ask and thank, and tell formal from informal',
          },
          {
            id: 'greet-4-apology',
            order: 4,
            titleFa: 'عذرخواهی',
            titleRo: 'Scuze',
            canFa: 'می‌تواند عذرخواهی کند',
            canEn: 'Can apologise',
          },
          {
            id: 'greet-5-how-are-you',
            order: 5,
            titleFa: 'حالت چطور است',
            titleRo: 'Ce mai faci?',
            canFa: 'می‌تواند احوال‌پرسی کند و جواب بدهد',
            canEn: 'Can ask how someone is, and answer',
          },
          {
            id: 'greet-6-introduce',
            order: 6,
            titleFa: 'معرفی خود',
            titleRo: 'Prezentarea',
            canFa: 'می‌تواند خودش را معرفی کند — اولین گفت‌وگوی کامل',
            canEn: 'Can introduce themselves — the first complete conversation',
          },
          {
            id: 'greet-7-the-words',
            order: 7,
            titleFa: 'واژه‌های پشت این عبارت‌ها',
            titleRo: 'Cuvintele',
            canFa: 'می‌تواند ببیند این عبارت‌ها از چه ساخته شده‌اند',
            canEn: 'Can see what those set phrases are built from',
          },
        ],
      },
      {
        id: 'core-numbers',
        slug: 'numere',
        titleFa: 'اعداد',
        titleRo: 'Numere',
        order: 2,
        steps: [
          {
            id: 'num-1-one-two',
            order: 1,
            titleFa: 'یک و دو — و جنسیت',
            titleRo: 'Unu și doi',
            canFa: 'می‌تواند بشمارد یک و دو، و بفهمد چرا دو شکل دارند',
            canEn: 'Can count one and two, and see why each has two forms',
          },
          {
            id: 'num-2-zero-ten',
            order: 2,
            titleFa: 'صفر تا ده',
            titleRo: 'Zero–zece',
            canFa: 'می‌تواند تا ده بشمارد',
            canEn: 'Can count to ten',
          },
          {
            id: 'num-3-teens',
            order: 3,
            titleFa: 'یازده تا نوزده',
            titleRo: 'Unsprezece–nouăsprezece',
            canFa: 'می‌تواند تا نوزده بشمارد',
            canEn: 'Can count to nineteen',
          },
          {
            id: 'num-4-tens',
            order: 4,
            titleFa: 'دهگان',
            titleRo: 'Zecile',
            canFa: 'می‌تواند تا نود بشمارد',
            canEn: 'Can count to ninety',
          },
          {
            id: 'num-5-hundred-thousand',
            order: 5,
            titleFa: 'صد و هزار',
            titleRo: 'Sută și mie',
            canFa: 'می‌تواند عددهای بزرگ بگوید',
            canEn: 'Can say large numbers',
          },
          {
            id: 'num-6-ordinals-first',
            order: 6,
            titleFa: 'اول تا سوم',
            titleRo: 'Primul–al treilea',
            canFa: 'می‌تواند ترتیب بگوید',
            canEn: 'Can say first, second, third',
          },
          {
            id: 'num-7-ordinals-mid',
            order: 7,
            titleFa: 'چهارم تا هفتم',
            titleRo: 'Al patrulea–al șaptelea',
            canFa: 'می‌تواند ترتیب را ادامه دهد',
            canEn: 'Can carry the ordinals on',
          },
          {
            id: 'num-8-ordinals-last',
            order: 8,
            titleFa: 'هشتم تا دهم',
            titleRo: 'Al optulea–al zecelea',
            canFa: 'می‌تواند ترتیب را تا ده تمام کند',
            canEn: 'Can finish the ordinals to tenth',
          },
        ],
      },
      {
        id: 'core-time',
        slug: 'timp',
        titleFa: 'زمان',
        titleRo: 'Timp',
        order: 3,
        steps: [
          {
            id: 'time-1-days',
            order: 1,
            titleFa: 'روزهای هفته',
            titleRo: 'Zilele săptămânii',
            canFa: 'می‌تواند روز هفته را بگوید',
            canEn: 'Can name the day of the week',
          },
          {
            id: 'time-2-months-first',
            order: 2,
            titleFa: 'ماه‌ها — نیمه‌ی اول',
            titleRo: 'Lunile I',
            canFa: 'می‌تواند شش ماه اول سال را بگوید',
            canEn: 'Can name the first six months',
          },
          {
            id: 'time-3-months-second',
            order: 3,
            titleFa: 'ماه‌ها — نیمه‌ی دوم',
            titleRo: 'Lunile II',
            canFa: 'می‌تواند سال را تمام کند',
            canEn: 'Can finish the year',
          },
          {
            id: 'time-4-clock',
            order: 4,
            titleFa: 'ساعت',
            titleRo: 'Ceasul',
            canFa: 'می‌تواند ساعت را بپرسد و بگوید',
            canEn: 'Can ask and tell the time',
          },
          {
            id: 'time-5-today',
            order: 5,
            titleFa: 'امروز، فردا، دیروز',
            titleRo: 'Azi, mâine, ieri',
            canFa: 'می‌تواند درباره‌ی روزهای نزدیک حرف بزند',
            canEn: 'Can talk about today, tomorrow and yesterday',
          },
          {
            id: 'time-6-periods',
            order: 6,
            titleFa: 'دوره‌ها و زود و دیر',
            titleRo: 'Perioade',
            canFa: 'می‌تواند بازه‌های زمانی را بگوید',
            canEn: 'Can name spans of time, and early and late',
          },
          {
            id: 'time-7-day-parts',
            order: 7,
            titleFa: 'بخش‌های روز',
            titleRo: 'Părțile zilei',
            canFa: 'می‌تواند بگوید صبح، بعدازظهر، شب',
            canEn: 'Can say morning, afternoon, evening',
          },
        ],
      },
      {
        id: 'core-question-words',
        slug: 'cuvinte-interogative',
        titleFa: 'کلمات پرسشی',
        titleRo: 'Cuvinte interogative',
        order: 4,
        steps: [
          {
            id: 'qw-1-plain',
            order: 1,
            titleFa: 'پرسش‌های بدون صرف',
            titleRo: 'Întrebări invariabile',
            canFa: 'می‌تواند چه، کِی، چگونه بپرسد',
            canEn: 'Can ask what, when and how',
          },
          {
            id: 'qw-2-cat',
            order: 2,
            titleFa: 'خانواده‌ی cât',
            titleRo: 'Familia cât',
            canFa: 'می‌تواند چقدر و چندتا بپرسد، با مطابقت جنسیت',
            canEn: 'Can ask how much and how many, with gender agreement',
          },
          {
            id: 'qw-3-who-which',
            order: 3,
            titleFa: 'که و کدام و چرا',
            titleRo: 'Cine, care, de ce',
            canFa: 'می‌تواند درباره‌ی شخص و علت بپرسد',
            canEn: 'Can ask about a person and a reason',
          },
        ],
      },
      {
        id: 'core-pronouns',
        slug: 'pronume',
        titleFa: 'ضمایر',
        titleRo: 'Pronume',
        order: 5,
        steps: [
          {
            id: 'pron-1-subject',
            order: 1,
            titleFa: 'من، تو، ما، شما',
            titleRo: 'Pronume subiect',
            canFa: 'می‌تواند فاعل را بگوید — و ببیند کِی حذفش کند',
            canEn: 'Can name the subject — and see when to drop it',
          },
          {
            id: 'pron-2-clitics',
            order: 2,
            titleFa: 'پی‌بست‌های اول و دوم شخص',
            titleRo: 'Clitice I–II',
            canFa: 'می‌تواند مرا، به من، تو را، به تو بگوید',
            canEn: 'Can say me, to me, you, to you',
          },
          {
            id: 'pron-3-third',
            order: 3,
            titleFa: 'سوم‌شخص و صورت احترامی',
            titleRo: 'Persoana a III-a',
            canFa: 'می‌تواند درباره‌ی دیگران حرف بزند و مؤدبانه خطاب کند',
            canEn: 'Can talk about other people, and address someone politely',
          },
          {
            id: 'pron-4-possessive',
            order: 4,
            titleFa: 'مالِ من',
            titleRo: 'Posesiv',
            canFa: 'می‌تواند بگوید چیزی مال اوست',
            canEn: 'Can say that something is theirs',
          },
        ],
      },
    ],
    sourcingPolicy: 'common-usage-ok',
    categories: ['everyday', 'transport', 'shopping', 'healthcare', 'emergency'],
    maxItems: 250,
  },
  {
    id: 'banking',
    titleFa: 'بانک',
    titleEn: 'Banking',
    order: 4,
    estimatedWeeks: 1,
    stationOrder: 'sequential',
    stations: [],
    sourcingPolicy: 'common-usage-ok',
    categories: ['banking'],
  },
  {
    id: 'healthcare',
    titleFa: 'پزشک و درمان',
    titleEn: 'Healthcare',
    order: 6,
    estimatedWeeks: 2,
    stationOrder: 'sequential',
    stations: [],
    sourcingPolicy: 'must-be-sourced',
    categories: ['healthcare'],
  },
  {
    id: 'administration',
    titleFa: 'امور اداری',
    titleEn: 'Administration',
    order: 7,
    estimatedWeeks: 2,
    stationOrder: 'sequential',
    stations: [],
    sourcingPolicy: 'must-be-sourced',
    categories: ['administration'],
  },
  {
    id: 'school',
    titleFa: 'مدرسه',
    titleEn: 'School',
    order: 8,
    estimatedWeeks: 1,
    stationOrder: 'grouped',
    stations: [],
    sourcingPolicy: 'common-usage-ok',
    categories: ['school'],
  },
];

export const SEED_WORDS: RomanianWord[] = [
  {
    id: 'w-cont',
    lemma: 'cont',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'contul',
    plural: 'conturi',
    translations: { en: 'account', fa: 'حساب' },
    domains: ['core'],
    intendedUse: 'produce',
    source: { kind: 'common-usage', label: 'DORVIA seed' },
    reviewer: 'ai-only',
    status: 'published',
  },
  {
    id: 'w-pasaport',
    lemma: 'pașaport',
    pos: 'noun',
    gender: 'n',
    definiteForm: 'pașaportul',
    plural: 'pașapoarte',
    translations: { en: 'passport', fa: 'گذرنامه' },
    domains: ['core'],
    intendedUse: 'produce',
    source: { kind: 'common-usage', label: 'DORVIA seed' },
    reviewer: 'ai-only',
    status: 'published',
  },
  {
    id: 'w-incet',
    lemma: 'încet',
    pos: 'adv',
    translations: { en: 'slowly / quietly', fa: 'آهسته / آرام' },
    domains: ['core'],
    intendedUse: 'produce',
    source: {
      kind: 'common-usage',
      label: "dexonline (DEX '09 / DOOM 3)",
      url: 'https://dexonline.ro/definitie/%C3%AEncet',
      retrievedAt: '2026-09-25',
    },
    reviewer: 'ai-only',
    status: 'draft',
    usageNote: {
      fa: [
        { t: 'قید به معنای «آرام، آهسته، بی‌صدا». در عبارت‌هایی چون «' },
        { ref: 'w-core-mai-adv', display: 'mai' },
        { t: ' ' },
        { ref: 'w-incet', display: 'încet' },
        { t: '» به کار می‌رود.' },
      ],
      en: [
        { t: 'Adverb meaning ' },
      ],
    },
  },
];

export const SEED_VERBS: RomanianVerb[] = [
  {
    id: 'v-a-fi',
    infinitive: 'a fi',
    translations: { en: 'to be', fa: 'بودن' },
    domains: ['core'],
    conjugation: {
      prezent: {
        eu: 'sunt',
        tu: 'ești',
        el: 'este',
        noi: 'suntem',
        voi: 'sunteți',
        ei: 'sunt',
      },
      conjunctiv: {
        eu: 'fiu',
        tu: 'fii',
        el: 'fie',
        noi: 'fim',
        voi: 'fiți',
        ei: 'fie',
      },
    },
    participiu: 'fost',
    source: {
      label: 'dexonline — paradigma (DOOM 3)',
      url: 'https://dexonline.ro/definitie/fi/paradigma',
      retrievedAt: '2026-09-22',
    },
    reviewer: 'ai-only',
    status: 'published',
  },
  {
    id: 'v-a-avea',
    infinitive: 'a avea',
    translations: { en: 'to have', fa: 'داشتن' },
    domains: ['core'],
    conjugation: {
      prezent: {
        eu: 'am',
        tu: 'ai',
        el: 'are',
        noi: 'avem',
        voi: 'aveți',
        ei: 'au',
      },
      conjunctiv: {
        eu: 'am',
        tu: 'ai',
        el: 'aibă',
        noi: 'avem',
        voi: 'aveți',
        ei: 'aibă',
      },
    },
    participiu: 'avut',
    source: {
      label: "dexonline — paradigma (DEX '09)",
      url: 'https://dexonline.ro/definitie/avea/paradigma',
      retrievedAt: '2026-09-22',
    },
    reviewer: 'ai-only',
    status: 'published',
  },
];

export const SEED_GRAPHEMES: RomanianGrapheme[] = [];

export const SEED_DIALOGUES: RomanianDialogue[] = [];
