import { RomanianPhrase } from '@/lib/romanian/types';

export const STAGE0_PHRASES: RomanianPhrase[] = [
  {
    id: 'everyday-004',
    slug: 'nu-vorbesc-romaneste',
    category: 'everyday',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Nu vorbesc românește.',
      en: "I don't speak Romanian.",
      fa: 'رومانیایی صحبت نمیکنم.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-005',
    slug: 'vorbiti-engleza',
    category: 'everyday',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'Vorbiți engleză?',
      en: 'Do you speak English?',
      fa: 'انگلیسی صحبت میکنید؟',
    },
    informalVariant: {
      ro: 'Vorbești engleză?',
      note: 'صورت غیررسمی — برای درک، نه برای گفتن.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-006',
    slug: 'la-revedere',
    category: 'everyday',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'La revedere!',
      en: 'Goodbye!',
      fa: 'خداحافظ!',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-007',
    slug: 'va-rog',
    category: 'everyday',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'Vă rog.',
      en: 'Please.',
      fa: 'لطفاً.',
    },
    informalVariant: {
      ro: 'Te rog.',
      note: 'صورت غیررسمی — برای درک، نه برای گفتن.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-008',
    slug: 'multumesc',
    category: 'everyday',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Mulțumesc.',
      en: 'Thank you.',
      fa: 'ممنون.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-009',
    slug: 'cu-placere',
    category: 'everyday',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Cu plăcere.',
      en: "You're welcome.",
      fa: 'خواهش میکنم.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-010',
    slug: 'scuzati-ma',
    category: 'everyday',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'Scuzați-mă.',
      en: 'Excuse me.',
      fa: 'ببخشید.',
    },
    informalVariant: {
      ro: 'Scuză-mă.',
      note: 'صورت غیررسمی — برای درک، نه برای گفتن.',
    },
    usageNote: {
      fa: 'در رومانی برای صدا زدن یک غریبه در خیابان، اغلب بهجای «ببخشید» با «Bună ziua» شروع میکنند.',
      en: 'In Romania, people often open with “Bună ziua” rather than “excuse me” when approaching a stranger.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-011',
    slug: 'imi-pare-rau',
    category: 'everyday',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Îmi pare rău.',
      en: "I'm sorry.",
      fa: 'متأسفم.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-012',
    slug: 'vorbiti-mai-rar',
    category: 'everyday',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'Puteți vorbi mai rar, vă rog?',
      en: 'Could you speak more slowly, please?',
      fa: 'میتوانید آهستهتر صحبت کنید؟',
    },
    informalVariant: {
      ro: 'Poți vorbi mai rar?',
      note: 'صورت غیررسمی — برای درک، نه برای گفتن.',
    },
    usageNote: {
      fa: '«mai încet» نگویید — آن یعنی «آرامتر/بیصداتر»، نه «آهستهتر».',
      en: 'Do not say “mai încet” — that means “more quietly”, not “more slowly”.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-013',
    slug: 'ce-inseamna',
    category: 'everyday',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'Ce înseamnă asta, vă rog?',
      en: 'What does this mean, please?',
      fa: 'این یعنی چه؟',
    },
    usageNote: {
      fa: 'حتماً با «vă rog» گفته شود؛ صورت خالی با لحن تخت میتواند پرخاشگرانه شنیده شود.',
      en: 'Always say it with “vă rog”; the bare form with flat intonation can sound confrontational.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-014',
    slug: 'cum-se-spune',
    category: 'everyday',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Cum se spune în română?',
      en: 'How do you say it in Romanian?',
      fa: 'به رومانیایی چه میشود؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'everyday-015',
    slug: 'puteti-scrie',
    category: 'everyday',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'Puteți scrie, vă rog?',
      en: 'Could you write it down, please?',
      fa: 'میتوانید بنویسید، لطفاً؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'transport-003',
    slug: 'unde-este',
    category: 'transport',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Unde este?',
      en: 'Where is it?',
      fa: 'کجاست؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'transport-004',
    slug: 'unde-este-toaleta',
    category: 'transport',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Unde este toaleta?',
      en: 'Where is the toilet?',
      fa: 'سرویس بهداشتی کجاست؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'healthcare-002',
    slug: 'unde-este-o-farmacie',
    category: 'healthcare',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Unde este o farmacie?',
      en: 'Where is a pharmacy?',
      fa: 'داروخانه کجاست؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'transport-005',
    slug: 'este-departe',
    category: 'transport',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Este departe?',
      en: 'Is it far?',
      fa: 'دور است؟',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'shopping-003',
    slug: 'aveti',
    category: 'shopping',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'Aveți?',
      en: 'Do you have it?',
      fa: 'دارید؟',
    },
    informalVariant: {
      ro: 'Ai?',
      note: 'صورت غیررسمی — برای درک، نه برای گفتن.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'shopping-004',
    slug: 'doar-ma-uit',
    category: 'shopping',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Doar mă uit, mulțumesc.',
      en: "I'm just looking, thank you.",
      fa: 'فقط نگاه میکنم، ممنون.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'shopping-005',
    slug: 'o-sticla-de-apa',
    category: 'shopping',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'O sticlă de apă, vă rog.',
      en: 'A bottle of water, please.',
      fa: 'یک بطری آب، لطفاً.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'emergency-002',
    slug: 'ajutor',
    category: 'emergency',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Ajutor!',
      en: 'Help!',
      fa: 'کمک!',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'emergency-003',
    slug: 'sunati-la-112',
    category: 'emergency',
    level: 'beginner',
    register: 'formal',
    text: {
      ro: 'Sunați la 112, vă rog.',
      en: 'Call 112, please.',
      fa: 'لطفاً به ۱۱۲ زنگ بزنید.',
    },
    source: {
      kind: 'official',
      label: 'Numărul unic de urgență 112 (România)',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'emergency-004',
    slug: 'm-am-ratacit',
    category: 'emergency',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'M-am rătăcit.',
      en: "I'm lost.",
      fa: 'گم شدهام.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
  {
    id: 'healthcare-003',
    slug: 'nu-ma-simt-bine',
    category: 'healthcare',
    level: 'beginner',
    register: 'neutral',
    text: {
      ro: 'Nu mă simt bine.',
      en: "I don't feel well.",
      fa: 'حالم خوب نیست.',
    },
    source: {
      kind: 'common-usage',
      label: 'DORVIA Stage 0 — AI-authored, not natively reviewed',
    },
    reviewer: 'ai-only',
    status: 'published',
    lastReviewed: null,
    isFree: true,
  },
];
