'use client';

import React from 'react';
import type { Language } from '@/types';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { PronunciationAudio } from '@/components/romanian/PronunciationAudio';

import { additionalFoundationLessons, type AdditionalFoundationSlug } from '@/content/romanian/additional-foundation-lessons';

const stages = [{fa:'هدف',en:'Goal'},{fa:'شنیدن',en:'Listen'},{fa:'قاعده',en:'Rule'},{fa:'نوشتن',en:'Write'},{fa:'گفتن و مرور',en:'Speak and review'}];
const minutes = [2,3,4,4,2];
function normalize(value:string) { return value.normalize('NFC').trim().toLocaleLowerCase('ro-RO').replace(/[.!?]+$/g,'').replace(/\s+/g,' '); }

export function AdditionalFoundationLesson({lang,slug}:{lang:Language;slug:AdditionalFoundationSlug}) {
  const isFa=lang==='fa'; const key=isFa?'fa':'en'; const copy=additionalFoundationLessons[slug];
  const [stage,setStage]=React.useState(0); const [index,setIndex]=React.useState(0); const [answer,setAnswer]=React.useState(''); const [checked,setChecked]=React.useState(false); const [passed,setPassed]=React.useState<number[]>([]); const [spoken,setSpoken]=React.useState(false);
  const allExamples=copy.rules.flatMap(rule=>rule.examples); const current=copy.practice[index]; const correct=normalize(answer)===normalize(current.answer);
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setChecked(true);if(correct)setPassed(previous=>previous.includes(index)?previous:[...previous,index]);}
  function nextPrompt(){if(index<copy.practice.length-1){setIndex(index+1);setAnswer('');setChecked(false);}else setStage(4);}
  return <div dir={isFa?'rtl':'ltr'} className="space-y-6">
    <Link href="/learn-romanian/fundamente" className="inline-flex text-sm font-bold text-[#1554bd] hover:underline">{isFa?'→ بازگشت به مسیر درس‌های پایه':'← Back to foundations'}</Link>
    <header className="dark-hero-panel space-y-3 rounded-3xl p-7 text-white sm:p-10"><p className="text-sm font-bold text-blue-100">{isFa?'درس پایه · یک نوبت حدود ۱۵ دقیقه':'Foundation lesson · about 15 minutes'}</p><h1 className="text-3xl font-extrabold sm:text-4xl">{copy.title[key]}</h1><p className="max-w-3xl leading-7 text-blue-50">{copy.goal[key]}</p></header>
    <article aria-labelledby="foundation-reference" className="space-y-6 rounded-3xl border-2 border-blue-200 bg-white p-5 shadow-sm sm:p-8">
      <div><p className="text-xs font-extrabold text-[#1554bd]">{isFa?'درسنامهٔ کامل · پیش از تمرین':'COMPLETE GUIDE · BEFORE PRACTICE'}</p><h2 id="foundation-reference" className="mt-1 text-2xl font-extrabold">{copy.title[key]}</h2><p className="mt-3 text-sm leading-7 text-slate-700">{copy.introduction[key]}</p></div>
      <div className="space-y-4">{copy.rules.map(rule=><section key={rule.title.en} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-5"><h3 className="font-extrabold text-slate-900">{rule.title[key]}</h3><p className="mt-2 text-sm leading-7 text-slate-700">{rule.explanation[key]}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{rule.examples.map(example=><div key={example.ro} className="rounded-xl bg-white p-3"><p lang="ro" dir="ltr" className="font-bold text-[#1554bd]">{example.ro}</p><p className="mt-1 text-xs text-slate-600">{example[key]}</p><PronunciationAudio currentLang={lang} label={example.ro} variant="compact" className="mt-2" /></div>)}</div></section>)}</div>
      <div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[430px] text-sm"><thead className="bg-blue-50"><tr>{copy.table.headers.map(header=><th key={header.en} className="p-3 text-start">{header[key]}</th>)}<th className="p-3 text-start">{isFa?'توضیح':'Note'}</th></tr></thead><tbody>{copy.table.rows.map((row,i)=><tr key={i} className="border-t border-slate-100">{row.cells.map((cell,j)=><td key={j} dir="auto" className="p-3 font-semibold">{cell}</td>)}<td className="p-3 text-slate-600">{row.note[key]}</td></tr>)}</tbody></table></div>
      <p className="rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950">{isFa?'هر نمونه را با معنی‌اش بخوانید، به تلفظ آن گوش دهید و سپس بدون نگاه به جدول یک جملهٔ تازه بسازید. جدول و قاعده در همهٔ مراحل همین‌جا در دسترس‌اند.':'Read each example with its meaning, listen, then make a new sentence without looking at the table. The guide remains available throughout the practice.'}</p>
    </article>
    <nav aria-label={isFa?'مراحل درس ۱۵ دقیقه‌ای':'15-minute lesson stages'} className="grid grid-cols-2 gap-2 rounded-2xl border border-slate-200 bg-white p-3 sm:grid-cols-5">{stages.map((label,i)=><button key={label.en} type="button" onClick={()=>setStage(i)} aria-current={stage===i?'step':undefined} className={`rounded-xl px-3 py-2 text-start text-xs font-bold ${stage===i?'bg-[#1554bd] text-white':'bg-slate-50 text-slate-700 hover:bg-blue-50'}`}>{i+1}. {label[key]}<span className="mt-1 block font-normal">{minutes[i]} {isFa?'دقیقه':'min'}</span></button>)}</nav>
    {stage===0&&<section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-extrabold">{isFa?'هدف این درس':'Your goal'}</h2><p className="leading-7">{copy.goal[key]}</p><p lang="ro" dir="ltr" className="rounded-xl bg-blue-50 p-4 text-lg font-bold text-[#1554bd]">{allExamples[0].ro}</p><button type="button" onClick={()=>setStage(1)} className="rounded-xl bg-[#1554bd] px-5 py-3 font-bold text-white">{isFa?'شنیدن نمونه‌ها ←':'Listen to examples →'}</button></section>}
    {stage===1&&<section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-extrabold">{isFa?'بشنوید و معنی را پیدا کنید':'Listen and identify meaning'}</h2><div className="grid gap-3 sm:grid-cols-2">{allExamples.map(example=><div key={example.ro} className="rounded-xl bg-blue-50 p-4"><p lang="ro" dir="ltr" className="font-bold">{example.ro}</p><p className="mt-1 text-sm">{example[key]}</p><PronunciationAudio currentLang={lang} label={example.ro} variant="compact" className="mt-2" /></div>)}</div><button type="button" onClick={()=>setStage(2)} className="rounded-xl bg-[#1554bd] px-5 py-3 font-bold text-white">{isFa?'بررسی قاعده ←':'Review the rule →'}</button></section>}
    {stage===2&&<section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-extrabold">{isFa?'الگو را در مثال‌ها پیدا کنید':'Find the pattern in examples'}</h2>{copy.rules.map(rule=><div key={rule.title.en} className="rounded-xl bg-slate-50 p-4"><h3 className="font-bold">{rule.title[key]}</h3><p className="mt-1 text-sm leading-7">{rule.explanation[key]}</p></div>)}<button type="button" onClick={()=>{setStage(3);setIndex(0);setAnswer('');setChecked(false);}} className="rounded-xl bg-[#1554bd] px-5 py-3 font-bold text-white">{isFa?'نوشتن جمله ←':'Write a sentence →'}</button></section>}
    {stage===3&&<section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-extrabold text-[#1554bd]">{isFa?`تمرین ${index+1} از ${copy.practice.length}`:`Practice ${index+1} of ${copy.practice.length}`}</p><h2 className="text-xl font-extrabold">{isFa?`«${current.meaning.fa}» را به رومانیایی بنویسید.`:`Write “${current.meaning.en}” in Romanian.`}</h2><form onSubmit={submit} className="flex flex-wrap gap-2"><input lang="ro" dir="ltr" autoComplete="off" aria-label={isFa?'جملهٔ رومانیایی':'Romanian sentence'} value={answer} onChange={event=>{setAnswer(event.target.value);setChecked(false);}} className="min-w-56 flex-1 rounded-xl border border-slate-300 p-3 text-lg" /><button type="submit" disabled={!answer.trim()} className="rounded-xl bg-[#1554bd] px-5 py-3 font-bold text-white disabled:opacity-50">{isFa?'بررسی':'Check'}</button></form>{checked&&<p role="status" className={`rounded-xl p-3 text-sm ${correct?'bg-emerald-50 text-emerald-900':'bg-amber-50 text-amber-950'}`}>{correct?(isFa?'درست است. جمله را یک بار بلند بخوانید.':'Correct. Say the sentence aloud once.'):current.hint[key]}</p>}{checked&&!correct&&<button type="button" onClick={()=>setAnswer(current.answer)} className="text-sm font-semibold text-[#1554bd] underline">{isFa?'نمایش پاسخ برای تمرین دوباره':'Show answer to retry'}</button>}{passed.includes(index)&&<button type="button" onClick={nextPrompt} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">{isFa?index<copy.practice.length-1?'تمرین بعدی ←':'گفتن و مرور ←':index<copy.practice.length-1?'Next exercise →':'Speak and review →'}</button>}</section>}
    {stage===4&&<section className="space-y-4 rounded-2xl border border-emerald-200 bg-white p-6"><h2 className="text-xl font-extrabold text-emerald-900">{isFa?'جمله‌ها را بلند بگویید و مرور کنید':'Say the sentences and review'}</h2>{copy.practice.map(item=><div key={item.answer} className="rounded-xl bg-emerald-50 p-4"><p lang="ro" dir="ltr" className="text-lg font-bold">{item.answer}</p><p className="text-sm">{item.meaning[key]}</p><PronunciationAudio currentLang={lang} label={item.answer} variant="compact" className="mt-2" /></div>)}<label className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm font-semibold"><input type="checkbox" checked={spoken} onChange={event=>setSpoken(event.target.checked)} className="h-5 w-5 accent-[#1554bd]" />{isFa?'جمله‌ها را با صدای بلند گفتم.':'I said the sentences aloud.'}</label>{spoken&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-900">{isFa?`${passed.length} جمله از ${copy.practice.length} جملهٔ نوشتاری درست بود.`:`${passed.length} of ${copy.practice.length} written sentences were correct.`}</p>}<Link href={copy.next} className="inline-flex rounded-xl bg-[#1554bd] px-5 py-3 font-bold text-white">{isFa?'درس بعدی ←':'Next lesson →'}</Link></section>}
  </div>;
}
