'use client';
import React from 'react';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { homeReturnDialogue, cafeReturnDialogue } from '@/content/romanian/family-story';
import { ListeningPractice } from './ListeningPractice';
import { StoryVerbTimes } from './StoryVerbTimes';
import { VoiceAnswer } from './VoiceAnswer';
import { AnswerWritingTip } from './AnswerWritingTip';
import { matchesRomanianAnswer } from '@/lib/romanian/answerFeedback';
import { playVerifiedAudio, stopVerifiedAudio } from '@/lib/romanian/playVerifiedAudio';

export function FamilyHomeReturn({ lang, visit = 'shop' }: { lang: 'fa' | 'en'; visit?: 'shop' | 'cafe' }) {
  const fa = lang === 'fa'; const cafe = visit === 'cafe'; const dialogue = cafe ? cafeReturnDialogue : homeReturnDialogue;
  const [round, setRound] = React.useState(0);
  const [answer, setAnswer] = React.useState('');
  const [feedback, setFeedback] = React.useState<'correct' | 'retry' | null>(null);
  const [hint, setHint] = React.useState(false);
  const [complete, setComplete] = React.useState(false);
  const [audioError, setAudioError] = React.useState(false);
  React.useEffect(() => () => stopVerifiedAudio(), []);
  const cue = dialogue[round * 2];
  const target = dialogue[round * 2 + 1];
  function check(value: string) { setAnswer(value); setFeedback(matchesRomanianAnswer(value, target.ro) ? 'correct' : 'retry'); }
  function next() { stopVerifiedAudio(); if (round === 1) { setComplete(true); return; } setRound(1); setAnswer(''); setFeedback(null); setHint(false); }
  const button = 'inline-flex min-h-12 items-center rounded-xl bg-[#1554bd] px-5 py-3 font-bold text-white disabled:opacity-50';
  return <div className="space-y-6" dir={fa ? 'rtl' : 'ltr'}>
    <header className="dark-hero-panel rounded-3xl p-7 text-white"><p>{cafe ? (fa ? 'بازگشت از کافه · مرور بدون واژهٔ تازه' : 'Back from the café · review without new words') : (fa ? 'بازگشت از فروشگاه · جلسهٔ مرور مستقل' : 'Back from the shop · a separate review session')}</p><h1 className="mt-2 text-3xl font-bold">{fa ? 'دوباره در خانهٔ خانواده' : 'Back at the family home'}</h1><p className="mt-3">{cafe ? (fa ? 'بعد از صبحانه با النا به خانه برگشته‌اید. آنا که در خانه مانده بود از نوشیدنی شما می‌پرسد. برای گفتنِ «داشتم»، am avut را از فعل آموخته‌شدهٔ a avea مرور کنید.' : 'You return home after breakfast with Elena. Ana stayed at home and asks about your drink. Review am avut, I had, from the already learned verb a avea.') : fa ? 'آب را به خانه آورده‌اید. آنا دربارهٔ خرید می‌پرسد؛ با واژه‌های خانه و جمله‌های فروشگاه پاسخ بدهید. قیمت پنج لِی فقط نمونهٔ آموزشی است.' : 'You have brought the water home. Ana asks about your shopping; answer using the home vocabulary and shop sentences. Five lei is only a practice price.'}</p></header>
    <section className="space-y-4 rounded-2xl border bg-white p-5"><p className="rounded-xl bg-sky-50 p-3 text-sm">{fa ? 'آنا، زن‌عموی شما، صمیمی صحبت می‌کند: ai یعنی «داری». در فروشگاه و کافه aveți («دارید») خطاب مؤدبانه است. این بخش فقط مرور جمله‌های آموخته‌شده است.' : 'Ana now uses familiar address: ai means “you have”. Aveți is polite address in shops and cafés. This section only reviews learned sentences.'}</p><h2 className="text-xl font-bold">{fa ? 'گفت‌وگوی بازگشت را بشنوید' : 'Listen to the homecoming'}</h2><ListeningPractice lang={lang} scene="home" dialogue={dialogue} counterpart={{fa:'آنا',en:'Ana'}}/></section>
    {cafe && <aside className="space-y-2 rounded-xl bg-sky-50 p-4"><p>{fa ? 'در خانه، از تجربهٔ تمام‌شده صحبت می‌کنیم: am avut یعنی «داشتم»، ai avut یعنی «داشتی». فعل تازه‌ای اضافه نشده؛ این شکل گذشتهٔ a avea است.' : 'At home we talk about the completed outing: am avut means I had; ai avut means you had. This is the past of a avea, not a new verb.'}</p><p lang="ro" dir="ltr">Da, am avut ceai cu lapte.</p><p lang="en" dir="ltr">Yes, I had tea with milk.</p>{fa && <p>بله، چای با شیر داشتم.</p>}</aside>}
    {!complete ? <section className="space-y-4 rounded-2xl border bg-white p-5"><p className="text-sm font-semibold">{fa ? `پاسخ شما به آنا · ${round + 1} از ۲` : `Your answer to Ana · ${round + 1} of 2`}</p><h2 lang="ro" dir="ltr" className="text-xl font-bold">{cue.ro}</h2><p lang="en" dir="ltr">{cue.en}</p>{fa && <p>{cue.fa}</p>}<button type="button" className="min-h-11 text-[#1554bd] underline" onClick={() => playVerifiedAudio(cue.ro, () => setAudioError(true), undefined, cue.audioVoice)}>{fa ? 'شنیدن سؤال آنا' : 'Hear Ana’s question'}</button><form className="space-y-3" onSubmit={e=>{e.preventDefault();check(answer);}}><label htmlFor="return-answer" className="block font-semibold">{fa ? 'پاسخ رومانیایی' : 'Romanian answer'}</label><input id="return-answer" lang="ro" dir="ltr" value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback(null);}} className="w-full rounded-xl border p-3 text-lg focus:ring-2 focus:ring-blue-600"/><div className="flex flex-wrap gap-3"><button type="submit" disabled={!answer.trim()} className={button}>{fa ? 'بررسی' : 'Check'}</button><button type="button" className="min-h-12 rounded-xl border px-4 font-semibold" onClick={()=>setHint(true)}>{fa ? 'راهنما' : 'Hint'}</button></div></form><VoiceAnswer key={round} lang={lang} audioVoice={target.audioVoice} target={target.ro} onAnswer={check}/>{hint && <p lang="ro" dir="ltr" className="rounded-xl bg-blue-50 p-3">{target.ro}</p>}{feedback && <p role="status" className="rounded-xl bg-blue-50 p-3">{feedback==='correct' ? fa ? 'آفرین! پاسخ شما پذیرفته شد.' : 'Well done! Your answer is accepted.' : fa ? 'یک بار دیگر تلاش کنید؛ صدای نمونه و راهنما کمک می‌کنند.' : 'Try again; the model audio and hint can help.'}</p>}{feedback==='correct' && <><AnswerWritingTip lang={lang} answer={answer} target={target.ro}/><button type="button" className={button} onClick={next}>{round===0 ? fa ? 'سؤال بعدی آنا' : 'Ana’s next question' : fa ? 'پایان این قسمت' : 'Finish this episode'}</button></>}</section> : <section className="space-y-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="text-2xl font-bold">{fa ? 'یک داستان کامل را تجربه کردید' : 'You experienced a complete story'}</h2><p>{cafe ? (fa ? 'در خانه دربارهٔ صبحانه صحبت کردید، در کافه چای سفارش دادید و در خانه دوباره همان جمله‌ها را تمرین کردید.' : 'You talked about breakfast at home, ordered tea at the café and practised the same sentences back at home.') : fa ? 'وارد خانه شدید، با خانواده آشنا شدید، خرید کردید و به خانه برگشتید. حالا می‌توانید بخش‌های همین داستان را دوباره تمرین کنید.' : 'You entered the home, met the family, went shopping and returned home. You can now practise any part of the story again.'}</p><button type="button" className={button} onClick={()=>{stopVerifiedAudio();setComplete(false);setRound(0);setAnswer('');setFeedback(null);setHint(false);}}>{fa ? 'تمرین دوبارهٔ بازگشت' : 'Practise the homecoming again'}</button></section>}
    {complete && !cafe && <StoryVerbTimes lang={lang}/>}
    {complete && !cafe && <aside className="space-y-3 rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-bold">{fa ? 'داستان در صبح بعد ادامه دارد' : 'The story continues the next morning'}</h2><Link href="/learn-romanian/lectie/acasa/mic-dejun" className={button}>{fa ? 'درس ۴: صبحانه با خانواده' : 'Lesson 4: breakfast with the family'}</Link><p>{fa ? 'می‌توانید این درس را در جلسهٔ بعد انجام دهید.' : 'You can do this in your next session.'}</p></aside>}
    {complete && cafe && <aside className="space-y-3 rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-bold">{fa ? 'ادامهٔ روز در خانه' : 'Continue the day at home'}</h2><p>{fa ? 'در جلسهٔ بعد به آنا برای چیدن میز کمک کنید؛ پنج واژه یا فعل تازه در یک موقعیت کوتاه.' : 'In your next session, help Ana set the table; five new words or verbs in one short situation.'}</p><Link href="/learn-romanian/lectie/acasa/la-masa" className={button}>{fa ? 'درس ۵: کمک در چیدن میز' : 'Lesson 5: helping set the table'}</Link></aside>}
    {audioError && <p role="status">{fa ? 'صدا پخش نشد؛ دوباره تلاش کنید.' : 'Audio did not play; please try again.'}</p>}
    <div className="flex flex-wrap gap-4"><Link href="/learn-romanian/lectie/acasa/bun-venit" className="min-h-11 text-[#1554bd] underline">{fa ? 'شروع دوباره از ورود به خانه' : 'Start again at the front door'}</Link><Link href="/learn-romanian/lectie/tema/home" className="min-h-11 text-[#1554bd] underline">{fa ? 'درس‌های در خانه' : 'At-home lessons'}</Link></div>
  </div>;
}
