'use client';

import React from 'react';
import { usePathname } from 'next/navigation';
import { GRAMMAR_TOPICS, GRAMMAR_NOUNS, GRAMMAR_PERSONS, grammarWords, grammarVerbsFor, isGrammarLessonPath, type GrammarCopy, type GrammarExample } from '@/content/romanian/lesson-grammar';
import { PronunciationAudio } from './PronunciationAudio';
import audio from '@/content/romanian/verified-audio.json';

type LessonContext = { path: string; examples: readonly GrammarExample[] };
const GrammarContext = React.createContext<((examples:readonly GrammarExample[])=>()=>void) | null>(null);
export function useLessonGrammar(examples:readonly GrammarExample[]) {
  const register=React.useContext(GrammarContext);
  React.useEffect(()=>register?.(examples),[register,examples]);
}
function Copy({copy,fa}:{copy:GrammarCopy;fa:boolean}) {
  return <div className="space-y-1 text-sm leading-7">{fa&&<p>{copy.fa}</p>}<p lang="en" dir="ltr" className={fa?'text-xs leading-6 text-slate-600':''}>{copy.en}</p></div>;
}
function Sample({sample,fa}:{sample:GrammarExample;fa:boolean}) {
 const hasAudio=Object.hasOwn(audio,sample.ro);
 return <div className="rounded-xl border border-blue-100 bg-blue-50/40 p-3"><p lang="ro" dir="ltr" className="font-bold text-[#1554bd]">{sample.ro}</p><p lang="en" dir="ltr" className="mt-1 text-sm text-slate-600">{sample.en}</p>{fa&&<p className="mt-1 text-sm">{sample.fa}</p>}{hasAudio&&<PronunciationAudio currentLang={fa?'fa':'en'} label={sample.ro} variant="compact" className="mt-2"/>}</div>;
}
export function LessonGrammarBoundary({children}:{children:React.ReactNode}) {
 const path=usePathname();
 const fa=path.startsWith('/fa/');
 const [context,setContext]=React.useState<LessonContext|null>(null);
 const register=React.useCallback((examples:readonly GrammarExample[])=>{
  const value={path,examples};setContext(value);
  return ()=>setContext(current=>current===value?null:current);
 },[path]);
 const active=isGrammarLessonPath(path);
 const examples=context?.path===path?context.examples:[];
 const text=examples.map(e=>e.ro).join(' ');
 const words=grammarWords(text);
 const nouns=GRAMMAR_NOUNS.filter(n=>n.forms.some(f=>words.has(f)));
 const foundation=/\/(?:fundamente|alfabet)\//u.test(path)||path.endsWith('/un-o-doi-doua');
 const verbs=grammarVerbsFor(text,foundation);
 const hasHunger=words.has('foame');
 const hasImperative=examples.some(e=>/(?<!\p{L})(?:Intră|Adu)(?!\p{L})/u.test(e.ro));
 return <GrammarContext.Provider value={register}>
  {active&&<nav id="lesson-top" aria-label={fa?'دسترسی به درسنامهٔ گرامر':'Grammar guide access'} dir={fa?'rtl':'ltr'} className="mx-auto max-w-4xl px-4 pt-4"><a href="#lesson-grammar" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-semibold text-[#1554bd] focus-visible:outline focus-visible:outline-2">{fa?'قواعد، صرف فعل و منابع همین درس ↓':'Grammar, conjugation and lesson sources ↓'}</a></nav>}
  {children}
  {active&&<aside id="lesson-grammar" aria-labelledby="lesson-grammar-title" dir={fa?'rtl':'ltr'} className="mx-auto mb-10 max-w-4xl scroll-mt-6 px-4">
   <div className="space-y-5 rounded-3xl border border-blue-200 bg-white p-5 shadow-sm sm:p-7">
    <header><a href="#lesson-top" className="mb-3 inline-flex min-h-11 items-center text-sm font-semibold text-[#1554bd] underline">{fa?'بازگشت به درس ↑':'Back to the lesson ↑'}</a><p className="text-xs font-bold text-[#1554bd]">{fa?'مرجع همراه درس':'YOUR LESSON REFERENCE'}</p><h2 id="lesson-grammar-title" className="mt-2 text-2xl font-extrabold">{fa?'درسنامهٔ گرامر؛ معنی، شکل و کاربرد':'Grammar guide: meaning, form and use'}</h2><Copy fa={fa} copy={{fa:'یک نکتهٔ مرتبط با همین درس را باز کنید و در جملهٔ خودتان به کار ببرید. جدول‌ها برای مراجعه‌اند؛ حفظ همهٔ آن‌ها در یک جلسه لازم نیست و هدف پنج واژهٔ تازه تغییر نمی‌کند.',en:'Open one relevant point and use it in your own sentence. The tables are references, not one-session memorisation targets; the five-new-word goal stays the same.'}}/></header>
    {examples.length>0&&<details className="rounded-2xl border border-blue-100 bg-sky-50/50 p-4"><summary className="min-h-11 cursor-pointer content-center font-bold">{fa?'واژه و فعل را در همین مکالمه پیدا کنید':'Find words and verbs in this conversation'}</summary><div className="mt-4 space-y-4">{nouns.length>0&&<div className="grid gap-3 sm:grid-cols-2">{nouns.map(n=><div key={n.lemma} className="rounded-xl bg-white p-3"><p lang="ro" dir="ltr" className="font-bold">{n.lemma} · {n.gender==='m'?'masculin':n.gender==='f'?'feminin':'neutru'}</p><p lang="ro" dir="ltr" className="mt-1 text-sm">{n.gender==='f'?'o':'un'} {n.lemma} → {n.gender==='m'?'doi':'două'} {n.plural}</p><Copy fa={fa} copy={{fa:`صورت معین مفرد: ${n.definite}`,en:`Definite singular: ${n.definite}`}}/><a className="inline-flex min-h-11 items-center text-sm text-[#1554bd] underline" href={`https://dexonline.ro/definitie/${encodeURIComponent(n.lemma)}`} target="_blank" rel="noopener noreferrer">dexonline · {n.lemma}</a></div>)}</div>}<div className="grid gap-3 sm:grid-cols-2">{examples.filter(e=>/\b(?:am|ai|are|avem|aveți|sunt|este|ești|mergem|pun|cumpăr|aduc)\b/iu.test(e.ro)||/[?]/u.test(e.ro)).slice(0,4).map(e=><Sample key={e.ro} sample={e} fa={fa}/>)}</div></div></details>}
    <details className="rounded-2xl border border-emerald-200 bg-emerald-50/30 p-4"><summary className="min-h-11 cursor-pointer content-center font-bold">{fa?'صرف فعل؛ شخص، شمار و زمان':'Verb conjugation: person, number and tense'}</summary><div className="mt-4 space-y-4"><Copy fa={fa} copy={{fa:'مصدر نام فعل است؛ برای جمله باید صورت مناسب شخص را انتخاب کنید. eu «من»، tu «تو»، el / ea «او»، noi «ما»، voi «شما» و ei / ele «آن‌ها» هستند. خطاب محترمانهٔ dumneavoastră صورت voi را می‌گیرد، حتی برای یک نفر. e صورت کوتاه este است.',en:'The infinitive names the verb; a sentence needs a form that agrees with its subject. Eu = I, tu = you, el / ea = he / she, noi = we, voi = plural you, ei / ele = they. Polite dumneavoastră takes the voi form, even for one person. E is a short form of este.'}}/>
    {(verbs.length?verbs:grammarVerbsFor('',true)).map(v=><section key={v.lemma} className="rounded-xl border border-emerald-100 bg-white p-4"><h3 lang="ro" dir="ltr" className="font-bold">{v.lemma} · {v.meaning.en}{fa&&` · ${v.meaning.fa}`}</h3><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{GRAMMAR_PERSONS.map((p,i)=><div key={p} className="rounded-lg bg-slate-50 p-3"><p lang="ro" dir="ltr" className="text-xs text-slate-500">{p}</p><p lang="ro" dir="ltr" className="font-bold">{v.forms[i]}</p></div>)}</div><a href={`https://dexonline.ro/definitie/${encodeURIComponent(v.source)}`} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex min-h-11 items-center text-sm text-[#1554bd] underline">dexonline · {v.lemma}</a></section>)}
    {!foundation&&<div className="rounded-xl bg-amber-50 p-4"><Copy fa={fa} copy={{fa:'حال ساده می‌تواند با قید زمان، برنامهٔ آینده را هم برساند: Mâine cumpăr pâine. برای گذشتهٔ تمام‌شده، صورت کمکیِ am / ai / a / am / ați / au + اسم مفعول می‌آید: am cumpărat. این ați و a کمکی را با aveți و are در فعل مستقلِ داشتن یکی نگیرید. برای آیندهٔ ادبی: voi / vei / va / vom / veți / vor + مصدر بدون a؛ voi cumpăra. این‌ها مرور تکمیلی‌اند؛ نخست شکل همان مکالمه را تمرین کنید.',en:'A present form with a time word can express a future plan: Mâine cumpăr pâine. Completed past uses auxiliary am / ai / a / am / ați / au + a participle: am cumpărat. Distinguish auxiliary ați / a from independent aveți / are. Literary future uses voi / vei / va / vom / veți / vor + the infinitive without a: voi cumpăra. These are optional references; practise the form in the conversation first.'}}/></div>}
    </div></details>
    {hasHunger&&<details className="rounded-2xl border border-amber-200 p-4"><summary className="min-h-11 cursor-pointer content-center font-bold">{fa?'Mi-e foame؛ احساس گرسنگی و ضمیر داتیو':'Mi-e foame: hunger and the dative pronoun'}</summary><div className="mt-4 space-y-3"><Copy fa={fa} copy={{fa:'در Îmi este foame، îmi ضمیر کوتاه داتیو برای «من» و este فعل بودن است. صورت کوتاه: mi-e foame. برای «تو»: îți este foame → ți-e foame. در این ساختار به‌جای am از este / e استفاده می‌شود؛ foame مؤنث است، اما عبارت برای زن و مرد یکسان می‌ماند. خط تیره در mi-e اتصال ضمیر و شکل کوتاه فعل را نشان می‌دهد.',en:'In Îmi este foame, îmi is the short first-person dative pronoun and este is the verb to be. The contracted form is mi-e foame. For you: îți este foame → ți-e foame. Use este / e rather than am in this construction. Foame is feminine, but the expression does not change with the speaker’s gender. The hyphen joins the pronoun to the short verb.'}}/><Sample sample={{ro:'Da, mi-e foame.',en:'Yes, I am hungry.',fa:'بله، گرسنه‌ام.'}} fa={fa}/><a className="inline-flex min-h-11 items-center text-sm text-[#1554bd] underline" href="https://dexonline.ro/definitie/foame" target="_blank" rel="noopener noreferrer">dexonline · foame</a></div></details>}
    {hasImperative&&<details className="rounded-2xl border border-amber-200 p-4"><summary className="min-h-11 cursor-pointer content-center font-bold">{fa?'دعوت و درخواست؛ حال خبری با امر فرق دارد':'Invitations and requests: present versus imperative'}</summary><Copy fa={fa} copy={{fa:'Intră! دعوتِ «بیا داخل!» برای tu است؛ intru یعنی «من وارد می‌شوم». Adu! یعنی «بیاور!»؛ aduc یعنی «من می‌آورم». برای خطاب جمع یا محترمانه: intrați / aduceți. te rog خودمانی و vă rog محترمانه است. شکل امر را برای همهٔ فعل‌ها از روی یک پسوند حدس نزنید.',en:'Intră! invites one familiar person to enter; intru means I enter. Adu! means bring; aduc means I bring. Plural or polite forms are intrați / aduceți. Te rog is familiar and vă rog polite. Do not infer every imperative from one ending.'}}/></details>}
    {GRAMMAR_TOPICS.map(topic=><details key={topic.id} className="rounded-2xl border border-slate-200 p-4"><summary className="min-h-11 cursor-pointer content-center font-bold">{topic.title[fa?'fa':'en']}</summary><div className="mt-4 space-y-4"><Copy copy={topic.explanation} fa={fa}/><div role="region" aria-label={topic.title[fa?'fa':'en']} tabIndex={0} className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[480px] text-sm"><caption className="sr-only">{topic.title[fa?'fa':'en']}</caption><thead className="bg-slate-50"><tr>{topic.headers.map((h,i)=>!fa&&h.en==='Persian meaning'?null:<th scope="col" key={i} className="p-3 text-start">{h[fa?'fa':'en']}</th>)}</tr></thead><tbody>{topic.rows.map((row,i)=><tr key={i} className="border-t border-slate-100">{row.map((cell,j)=>!fa&&topic.headers[j].en==='Persian meaning'?null:<td key={j} dir="auto" className="p-3">{cell}</td>)}</tr>)}</tbody></table></div><div className="grid gap-3 sm:grid-cols-2">{topic.examples.map(e=><Sample key={e.ro} sample={e} fa={fa}/>)}</div><div className="rounded-xl bg-amber-50 p-3"><p className="mb-1 text-xs font-bold text-amber-900">{fa?'نکتهٔ مهم و خطای رایج':'Important point and common mistake'}</p><Copy copy={topic.warning} fa={fa}/></div><div className="flex flex-wrap gap-x-4">{topic.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center text-sm text-[#1554bd] underline">{source.label}</a>)}</div><p className="text-xs text-slate-500">Limba română pentru străini, A1–A2 (2020) · {fa?'صفحات':'pages'} {topic.bookPages}</p></div></details>)}
    <Copy fa={fa} copy={{fa:'در dexonline بخش تعریف، معنی را نشان می‌دهد و بخش paradigmă / flexiune صورت‌های واژه را. به منبع DEX / DOOM و نوع واژه توجه کنید؛ یک واژه ممکن است چند مدخل داشته باشد. توضیح آموزشی این صفحه بازنویسی برای زبان‌آموز است؛ جدول‌ها جای بررسی استثناهای فرهنگ را نمی‌گیرند.',en:'On dexonline, definitions explain meanings and paradigmă / flexiune shows word forms. Check the DEX / DOOM source and part of speech: one word may have several entries. This guide explains the patterns for learners; use the dictionary to check exceptions.'}}/>
   </div>
  </aside>}
 </GrammarContext.Provider>;
}
