'use client';

import React from 'react';
import { LessonStageNav } from './LessonStageNav';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { playVerifiedAudio, stopVerifiedAudio } from '@/lib/romanian/playVerifiedAudio';

type Locale = 'fa' | 'en';
type Line = { ro: string; en: string; fa: string; speaker: 'you' | 'shop'; recorded?: boolean };
const lines: Line[] = [
  { speaker: 'shop', ro: 'Bună ziua!', en: 'Hello!', fa: 'سلام!', recorded: true },
  { speaker: 'you', ro: 'O sticlă de apă, vă rog.', en: 'A bottle of water, please.', fa: 'یک بطری آب، لطفاً.', recorded: true },
  { speaker: 'you', ro: 'Cât costă?', en: 'How much does it cost?', fa: 'چقدر قیمت دارد؟', recorded: true },
  { speaker: 'shop', ro: 'Costă cinci lei.', en: 'It costs five lei.', fa: 'پنج لِی قیمت دارد.', recorded: true },
  { speaker: 'you', ro: 'Mulțumesc!', en: 'Thank you!', fa: 'متشکرم!', recorded: true },
];
const rounds = [
  { count: 1, target: 'O sticlă de apă, vă rog.', en: 'Ask for one bottle of water, please.', fa: 'یک بطری آب بخواهید.' },
  { count: 2, target: 'Două sticle de apă, vă rog.', en: 'Ask for two bottles of water, please.', fa: 'دو بطری آب بخواهید.' },
  { count: 3, target: 'Cât costă?', en: 'Ask how much it costs.', fa: 'قیمت را بپرسید.' },
] as const;
const labels = { fa: ['مکالمه', 'قاعده‌ها', 'یادآوری', 'خرید', 'نتیجه'], en: ['Conversation', 'Rules', 'Recall', 'Shop', 'Result'] };
const normalize = (s: string) => s.normalize('NFC').toLocaleLowerCase('ro-RO').trim().replace(/[.!?،,]+$/g, '').replace(/\s+/g, ' ');

export function ShopLesson({ lang }: { lang: Locale }) {
  const isFa = lang === 'fa';
  const [stage, setStage] = React.useState(0);
  const [round, setRound] = React.useState(0);
  const [answer, setAnswer] = React.useState('');
  const [result, setResult] = React.useState<'correct' | 'retry' | null>(null);
  const [showFa, setShowFa] = React.useState(true);
  const [hint, setHint] = React.useState(false);
  const [finished, setFinished] = React.useState(false);
  const [audioError, setAudioError] = React.useState(false);
  React.useEffect(() => () => stopVerifiedAudio(), []);
  const step = stage === 2 ? rounds[0] : rounds[round];
  function move(to: number) { stopVerifiedAudio(); setStage(to); setRound(0); setAnswer(''); setResult(null); setHint(false); setAudioError(false); }
  function play(ro: string) { setAudioError(false); playVerifiedAudio(ro, () => setAudioError(true)); }
  function check() { if (normalize(answer) === normalize(step.target)) setResult('correct'); else setResult('retry'); }
  function next() {
    if (stage === 2) { move(3); return; }
    if (round < rounds.length - 1) { setRound(round + 1); setAnswer(''); setResult(null); setHint(false); return; }
    try { localStorage.setItem('dorvia:romanian:shop:v1', new Date().toISOString()); } catch { /* optional */ }
    setFinished(true); move(4);
  }
  const button = (label: string, action: () => void) => <button type="button" onClick={action} className="rounded-xl bg-[#1554bd] px-5 py-3 font-bold text-white">{label}</button>;
  return <div className="space-y-6" dir={isFa ? 'rtl' : 'ltr'}>
    <header className="dark-hero-panel rounded-3xl p-7 text-white sm:p-10"><p className="text-sm font-semibold text-blue-100">{isFa ? 'خرید روزمره · درس ۱ · حدود ۱۵ دقیقه' : 'Everyday shopping · lesson 1 · about 15 minutes'}</p><h1 className="mt-2 text-3xl font-extrabold">{isFa ? 'خرید آب در فروشگاه' : 'Buying water in a shop'}</h1><p className="mt-3 text-blue-50">{isFa ? 'یک یا دو بطری آب بخواهید و قیمت را بپرسید.' : 'Ask for one or two bottles of water and ask the price.'}</p></header>
    <LessonStageNav lang={lang} labels={labels[lang]} stage={stage} onSelect={move} />
    {stage === 0 && <section className="space-y-5 rounded-2xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">{isFa ? '۱. گفت‌وگوی کوتاه را بشنوید' : '1. Listen to the short exchange'}</h2><p>{isFa ? 'فروشنده سلام می‌کند؛ شما آب می‌خواهید، قیمت را می‌پرسید و تشکر می‌کنید. قیمت پنج لِی فقط یک نمونهٔ آموزشی است.' : 'The seller greets you; you ask for water and the price, then thank them. Five lei is only an example price.'}</p><div className="space-y-3">{lines.map(line => <div key={`${line.speaker}-${line.ro}`} className={`rounded-xl p-4 ${line.speaker === 'you' ? 'bg-blue-50' : 'bg-slate-50'}`}><p className="text-xs font-bold text-[#1554bd]">{line.speaker === 'you' ? isFa ? 'شما' : 'You' : isFa ? 'فروشنده' : 'Seller'}</p><p lang="ro" dir="ltr" className="text-xl font-bold">{line.ro}</p><p lang="en" dir="ltr" className="text-sm text-slate-700">{line.en}</p>{isFa && showFa && <p className="text-sm">{line.fa}</p>}{line.recorded && <button type="button" onClick={() => play(line.ro)} className="mt-2 text-sm font-semibold text-[#1554bd] underline">{isFa ? 'شنیدن جمله' : 'Hear the line'}</button>}</div>)}</div>{isFa && <button type="button" className="text-sm text-[#1554bd] underline" onClick={() => setShowFa(!showFa)}>{showFa ? 'پنهان کردن ترجمهٔ فارسی' : 'نمایش ترجمهٔ فارسی'}</button>}<div>{button(isFa ? 'دیدن قاعده‌ها' : 'Explore the rules', () => move(1))}</div></section>}
    {stage === 1 && <section className="space-y-6 rounded-2xl border bg-white p-5 sm:p-7"><div><h2 className="text-xl font-bold">{isFa ? '۲. واژه و قاعده، بر اساس همین خرید' : '2. Words and rules for this purchase'}</h2><p className="mt-2 text-slate-600">{isFa ? 'هر بخش یک کاربرد دارد؛ ابتدا مثال را بخوانید و سپس شکل جمله را بررسی کنید.' : 'Each section has one use. Read the example, then notice the sentence pattern.'}</p></div>
      <article className="space-y-3 rounded-xl bg-sky-50 p-4"><h3 className="font-bold">{isFa ? 'درخواست مؤدبانه: کالا + vă rog' : 'Polite request: item + vă rog'}</h3><p>{isFa ? 'در خرید کوتاه می‌توانید نام کالا و مقدار آن را بگویید و «vă rog» را برای «لطفاً» در پایان بیاورید. در این ساختار فعل گفته نمی‌شود، اما درخواست کامل و طبیعی است.' : 'In a short purchase, state the item and quantity, then add “vă rog” (please). The verb is left unspoken, but this makes a natural request.'}</p><Example ro="O sticlă de apă, vă rog." en="A bottle of water, please." fa="یک بطری آب، لطفاً." isFa={isFa} recorded play={play} /></article>
      <article className="space-y-3 rounded-xl bg-emerald-50 p-4"><h3 className="font-bold">{isFa ? 'شمارش و جنس اسم: o sticlă → două sticle' : 'Quantity and noun gender: o sticlă → două sticle'}</h3><p>{isFa ? '«sticlă» اسم مؤنث است: برای «یک» از o و برای «دو» از două استفاده می‌کنیم. در جمع، پایان واژه نیز عوض می‌شود: sticlă → sticle. بنابراین «دو بطری» می‌شود două sticle؛ شکل «doi sticle» نادرست است.' : '“Sticlă” is feminine: use o for one and două for two. The noun changes in the plural: sticlă → sticle. Thus “two bottles” is două sticle, not “doi sticle”.'}</p><p>{isFa ? 'برای گفتن محتوی ظرف، de + نام ماده می‌آید: o sticlă de apă = یک بطری آب. در این عبارت apă جمع بسته نمی‌شود؛ تعداد بطری‌ها تغییر می‌کند.' : 'Use de + the substance for the contents: o sticlă de apă = a bottle of water. Here apă stays the same; the number of bottles changes.'}</p><Example ro="Două sticle de apă, vă rog." en="Two bottles of water, please." fa="دو بطری آب، لطفاً." isFa={isFa} recorded play={play} /></article>
      <article className="space-y-3 rounded-xl bg-amber-50 p-4"><h3 className="font-bold">{isFa ? 'پرسیدن قیمت: Cât costă?' : 'Asking the price: Cât costă?'}</h3><p>{isFa ? '«cât» یعنی «چقدر» و «costă» شکل سوم‌شخص فعل a costa در زمان حال است. می‌توانید فقط «Cât costă?» بپرسید و به کالای مورد اشاره برگردید؛ یا نام کالا را پس از فعل اضافه کنید. برای یک یا چند بطری، شکل سوم‌شخص costă یکسان است.' : '“Cât” means “how much”; “costă” is the third-person present form of a costa (to cost). Ask “Cât costă?” for an item you are pointing to, or put the item after the verb. The third-person form costă works with one or more bottles.'}</p><Example ro="Cât costă?" en="How much does it cost?" fa="چقدر قیمت دارد؟" isFa={isFa} recorded play={play} /><Example ro="Cât costă două sticle de apă?" en="How much do two bottles of water cost?" fa="دو بطری آب چقدر قیمت دارد؟" isFa={isFa} recorded play={play} /></article>
      <article className="space-y-3 rounded-xl bg-slate-50 p-4"><h3 className="font-bold">{isFa ? 'ترتیب و کاربرد جمله‌ها' : 'Order and use of the lines'}</h3><ol className="list-decimal space-y-1 ps-5"><li>{isFa ? 'سلام: Bună ziua!' : 'Greet: Bună ziua!'}</li><li>{isFa ? 'درخواست: O sticlă de apă, vă rog.' : 'Request: O sticlă de apă, vă rog.'}</li><li>{isFa ? 'پرسش قیمت: Cât costă?' : 'Ask the price: Cât costă?'}</li><li>{isFa ? 'پاسخ فروشنده: Costă cinci lei.' : 'Seller replies: Costă cinci lei.'}</li><li>{isFa ? 'پایان: Mulțumesc!' : 'Close: Mulțumesc!'}</li></ol><p className="text-sm text-slate-600">{isFa ? 'پاسخ فروشنده در نمونه: Costă cinci lei. یعنی «پنج لِی قیمت دارد». cinci عدد پنج و lei جمع leu، واحد پول رومانی، است. قیمت واقعی را از فروشنده بپرسید.' : 'Sample seller reply: Costă cinci lei. means “It costs five lei.” Cinci means five; lei is the plural of leu, Romania’s currency. Ask the seller for the actual price.'}</p></article>
      <div>{button(isFa ? 'تمرین از حافظه' : 'Recall from memory', () => move(2))}</div></section>}
    {(stage === 2 || stage === 3) && <section className="space-y-5 rounded-2xl border bg-white p-5 sm:p-7"><p className="text-sm font-bold text-[#1554bd]">{stage === 2 ? isFa ? '۳. یادآوری' : '3. Recall' : isFa ? `۴. خرید، نوبت ${round + 1} از ۳` : `4. Shop, round ${round + 1} of 3`}</p><h2 className="text-xl font-bold">{isFa ? step.fa : step.en}</h2><p className="text-sm text-slate-600">{isFa ? 'جمله را به رومانیایی بنویسید، سپس آن را با صدای بلند بخوانید.' : 'Write the sentence in Romanian, then say it aloud.'}</p><form onSubmit={e => { e.preventDefault(); check(); }} className="space-y-3"><label htmlFor="shop-answer" className="block font-semibold">{isFa ? 'پاسخ رومانیایی' : 'Romanian answer'}</label><input id="shop-answer" lang="ro" dir="ltr" autoComplete="off" value={answer} onChange={e => { setAnswer(e.target.value); setResult(null); }} className="w-full rounded-xl border border-slate-300 p-3 text-lg focus:outline-none focus:ring-2 focus:ring-[#1554bd]" /><div className="flex flex-wrap gap-3"><button type="submit" disabled={!answer.trim()} className="rounded-xl bg-[#1554bd] px-5 py-3 font-bold text-white disabled:opacity-50">{isFa ? 'بررسی' : 'Check'}</button><button type="button" onClick={() => setHint(true)} className="rounded-xl border px-5 py-3 font-semibold text-[#1554bd]">{isFa ? 'راهنما' : 'Hint'}</button></div></form>{hint && <p className="rounded-xl bg-blue-50 p-3" lang="ro" dir="ltr">{step.count === 3 ? 'Cât …?' : step.count === 2 ? 'Două sticle de …, vă rog.' : 'O sticlă de …, vă rog.'}</p>}{result && <p role="status" className={`rounded-xl p-3 ${result === 'correct' ? 'bg-emerald-50 text-emerald-900' : 'bg-amber-50 text-amber-900'}`}>{result === 'correct' ? isFa ? 'درست است. حالا جمله را بلند بگویید.' : 'Correct. Now say it aloud.' : isFa ? 'دوباره تلاش کنید؛ از بخش قاعده‌ها و راهنما کمک بگیرید.' : 'Try again; use the rules and hint.'}</p>}{result === 'correct' && button(stage === 2 ? isFa ? 'شروع خرید' : 'Start shopping' : round === 2 ? isFa ? 'نتیجه' : 'Result' : isFa ? 'مورد بعد' : 'Next item', next)}</section>}
    {stage === 4 && <section className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">{finished ? isFa ? 'خرید ساده را انجام دادید' : 'You completed a simple purchase' : isFa ? 'تمرین هنوز کامل نشده است' : 'The practice is not complete yet'}</h2><p>{isFa ? 'اکنون می‌توانید تعداد بطری را تغییر دهید، درخواست مؤدبانه کنید و قیمت را بپرسید.' : 'You can now change the bottle quantity, make a polite request, and ask the price.'}</p>{button(finished ? isFa ? 'تمرین دوباره' : 'Practise again' : isFa ? 'ادامهٔ تمرین' : 'Continue practice', () => move(finished ? 0 : 3))}<Link href="/learn-romanian/lectie" className="ms-3 inline-block text-[#1554bd] underline">{isFa ? 'مجموعه‌های مکالمه' : 'Conversation topics'}</Link></section>}
    {audioError && <p role="status" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{isFa ? 'فایل صدا در دسترس نیست.' : 'Audio recording is unavailable.'}</p>}
    <p className="text-xs text-slate-500">{isFa ? 'همهٔ جمله‌ها و نمونه‌های این درس صدای ضبط‌شده دارند. تمرین نوشتاری کیفیت تلفظ را نمره نمی‌دهد.' : 'All dialogue lines and examples in this lesson have recordings. The writing exercise does not score pronunciation.'}</p>
  </div>;
}
function Example({ ro, en, fa, isFa, recorded, play }: { ro: string; en: string; fa: string; isFa: boolean; recorded?: boolean; play?: (ro: string) => void }) { return <div className="rounded-lg bg-white/75 p-3"><p lang="ro" dir="ltr" className="text-lg font-bold">{ro}</p><p lang="en" dir="ltr" className="text-sm text-slate-700">{en}</p>{isFa && <p className="text-sm">{fa}</p>}{recorded && play && <button type="button" onClick={() => play(ro)} className="mt-2 text-sm font-semibold text-[#1554bd] underline">{isFa ? 'شنیدن' : 'Listen'}</button>}</div>; }
