import sitemap from '../src/app/sitemap';
import { ROUTE_REGISTRY } from '../src/lib/routeRegistry';

async function validateSitemapExclusion(): Promise<void> {
  console.log('================================================================');
  console.log('DORVIA Sitemap In-Memory Parity & Exclusion Audit (dre-p146)');
  console.log('================================================================');

  // 1. Audit ROUTE_REGISTRY entries
  const romanianKeys = Object.keys(ROUTE_REGISTRY).filter(k => k === 'learn-romanian' || k.startsWith('learn-romanian/'));
  console.log(`Auditing ${romanianKeys.length} registered Romanian learning routes in ROUTE_REGISTRY:`);

  if (romanianKeys.length !== 14) {
    console.error(`❌ FAILED: Expected exactly 14 routes in ROUTE_REGISTRY, found ${romanianKeys.length}`);
    process.exit(1);
  }

  for (const key of romanianKeys) {
    const config = ROUTE_REGISTRY[key];
    console.log(`  • "${key}": indexable=${config.indexable}, inSitemap=${config.inSitemap}`);
    if (config.inSitemap !== false || config.indexable !== false) {
      console.error(`❌ FAILED: Route "${key}" must have inSitemap: false and indexable: false`);
      process.exit(1);
    }
  }

  // 2. Execute sitemap() directly in-memory (independent of network/deployment/URL)
  console.log('\nExecuting sitemap() function directly in-memory...');
  const items = await sitemap();
  console.log(`Total URLs generated by sitemap(): ${items.length}`);

  const violations = items.filter(item => item.url.includes('learn-romanian'));

  if (violations.length > 0) {
    console.error(`❌ FAILED: Found ${violations.length} unexpected Romanian URL(s) in sitemap output:`);
    violations.forEach(v => console.error(`  - ${v.url}`));
    process.exit(1);
  }

  console.log('\n✅ ASSERTION PASSED:');
  console.log('  - Zero (0) Romanian learning URLs exist in sitemap() return data.');
  console.log('  - All 14 routes strictly flagged as indexable: false and inSitemap: false.');
  console.log('  - Exclusion strictly enforced by code logic before Google crawler ingestion.');
  process.exit(0);
}

validateSitemapExclusion().catch(err => {
  console.error('Unexpected error during sitemap assertion:', err);
  process.exit(1);
});
